### ISSUE TITLE
getobjgap not implemented

### ISSUE THREAD

**Issue by bbrunaud** [jump-dev/Gurobi.jl#102]
Hello

I could not get the gap out of a Gurobi model, I don't see the function implemented in the code.

regards

**Comment by luistertulino** [comment]
Hi bbrunaud.

I just faced this same problem. I found a improvised solution for it. According to the Documentation (see here: https://jump.readthedocs.io/en/latest/refmodel.html#methods), the bound can be computed by the formula |b - f| / | f |, where 
- b is the best bound, and can be obtained by getobjectivebound(m::Model)
- f is the best feasible objective value, and can be obtained by getobjectivevalue(m::Model)
- | . | is the abs function.
You'll get a number between 0 and 1.

Note: my version of JuMP is 0.18.

**Comment by odow** [comment]
Hi @luistertulino,

There is a [`MIPGap` parameter](http://www.gurobi.com/documentation/8.0/refman/mipgap.html#attr:MIPGap), so it should be sufficient to go (I haven't tested this):
```julia
getobjgap(model::GurobiMathProgModel) = get_dblattr(model.inner, "MIPGap")
```
We'll accept a PR implementing this (with tests). Let me know if you need help making the PR.
