### ISSUE TITLE
handling range constraints in mathprog interface

### ISSUE THREAD

**Issue by mlubin** [jump-dev/Gurobi.jl#14]
The gurobi function `addrangeconstrs` introduces an additional slack variable to the problem for each constraint added. To properly support this, we need to transform user-facing variable indices to Gurobi variable indices at the mathprog interface layer (or convince Gurobi to make this transparent at the C-interface level). Until then, I'm printing a appropriate warning when range constraints are used.

**Comment by philipithomas** [comment]
Is this still an open issue? It's from 2013

**Comment by mlubin** [comment]
Still an open issue, the Gurobi API hasn't changed afaik

**Comment by philipithomas** [comment]
We're running into a bug and may need this fixed. Do you have any workarounds for adding constraints?

**Comment by IainNZ** [comment]
Add two constraints instead of a range? Gurobi will then internally make it a range during presolve

**Comment by philipithomas** [comment]
Doh. Minor change and it worked perfectly. Thanks.
