### ISSUE TITLE
Gurobi ISV key

### ISSUE THREAD

**Issue by hsgan** [jump-dev/Gurobi.jl#151]
I am testing the use of Gurobi (via Julia) under the ISV program (http://www.gurobi.com/products/licensing-pricing/isv-program).

Gurobi said they don't have Julia examples on how to do it, but they have given me a Java example:
GRBEnv env = new GRBEnv("gurobi.log", "ISV Name", "Application Name", Expiration (integer), "Key Code");

Without any additional arguments, I believe this is how we define the the Gurobi env, and define a model with it:
env = Gurobi.Env()
m = Model(solver=GurobiSolver(env))

Can Gurobi.Env() take in arguments of the form described in the Java example?
I am currently on version 0.4.0 of the Gurobi package.

Thanks!!

**Comment by odow** [comment]
`Gurobi.Env()` is a wrapper around the Gurobi C API function:
https://github.com/JuliaOpt/Gurobi.jl/blob/9bf2a76e27c82198ab4b2ce387944d666e5618eb/src/grb_env.jl#L4-L22
You can find the C documentation here: http://www.gurobi.com/documentation/8.0/refman/c_grbloadenv.html
You should ask Gurobi for some C examples, then we can translate those to Gurobi.jl.

Also, just a reminder that Gurobi.jl is developed and maintained by volunteers in the community. If you want commercial support for Gurobi in Julia, please let them know!

**Comment by hsgan** [comment]
Here's the C example:
GRBisqp(&env, "gurobi.log", "ISV Name", "Application Name", Expiration (integer), "Key Code");

Noted re commercial support for Gurobi in Julia. Thanks!!

**Comment by odow** [comment]
Reopening since it this isn't implemented. Feel free to make any PRs that you need to get it working. There are lots of grb_ccall examples in the code that demonstrate how to wrap a C function.

**Comment by odow** [comment]
Gurobi.jl now wraps the complete C API. You can use that to create the relevant environment, and then pass it to `Gurobi.Optimizer(env)`.
