### ISSUE TITLE
Support general constraints

### ISSUE THREAD

**Issue by colinfang** [jump-dev/Gurobi.jl#155]
Does Gurobi.jl support general constraints such as `min`, `max`, `abs`, `or` ... already?

Btw, does JuMP even support them?

http://www.gurobi.com/documentation/7.5/refman/py_model_addgenconstrmin.html

**Comment by odow** [comment]
> Does Gurobi.jl support general constraints such as min, max, abs, or ... already?

No. However, `Gurobi.jl` wraps the Gurobi C API so you could make a pull request wrapping constraints such as http://www.gurobi.com/documentation/7.5/refman/c_grbaddgenconstrmin.html

I can walk you through the process if you need help.

> Btw, does JuMP even support them?

Not yet. However, the upcoming release of JuMP 0.19 will have much better support for extensions such as this.
