### ISSUE TITLE
Code implementation for retrieving the number of produced usercuts in a Infocallback

### ISSUE THREAD

**Issue by CBongiova** [jump-dev/Gurobi.jl#160]
Hello, 

I would like to propose an addition to the function "MPBWrapper.jl" to retrieve the number of generated usercuts during the B&B search. This is following the discussion at https://discourse.julialang.org/t/does-anyone-know-how-to-retrieve-the-number-of-generated-cuts-in-the-informational-callback/15370

Note that a Method to retrieve the number of generated cuts with Gurobi already exists in function "grb_callbacks.jl" (https://github.com/JuliaOpt/Gurobi.jl/blob/120d606da08facffb206d73d932dbb0bf7d7001d/src/grb_callbacks.jl#L110) 

Then, the only addition to be made is in the wrapper (https://github.com/JuliaOpt/Gurobi.jl/blob/120d606da08facffb206d73d932dbb0bf7d7001d/src/MPBWrapper.jl#L570) 

```
function cbgetmipcutcnt(d::GurobiCallbackData)
    @assert d.state == :Intermediate
    return cbget_mip_cutcnt(d.cbdata, d.where)
end

function cbgetmipcutcnt(d::GurobiCallbackData,output)
    @assert d.state == :Intermediate
    return cbget_mip_cutcnt(d.cbdata, d.where, output)
end
```

Then one could retrieve the number of generated usercuts in an Infocallback as follows:
```
#Produce an info callback
bbdata = Vector{Float64}[]
function infocallback(cb)
node = MathProgBase.cbgetexplorednodes(cb)
obj = MathProgBase.cbgetobj(cb)
bestbound = MathProgBase.cbgetbestbound(cb)
gap=(abs(bestbound-obj)/abs(obj))*100
**numcuts = Gurobi.cbgetmipcutcnt(cb)**
push!(bbdata, [time(), node, obj, bestbound, gap, numcuts])
end
addinfocallback(m, infocallback, when = :Intermediate)
```

I don't know how to make a pull request. Could anyone help me on that?

**Comment by odow** [comment]
Hi @CBongiova,

Sorry for missing this. If you're still interested, the easiest way to make a pull request is through the web-interface. Here are the steps

1. Make the changes locally and test that they work. 
2. Navigate to a file like [`grb_callbacks.jl`](https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/grb_callbacks.jl) in the web-interface
3. Click the pencil in the top-right of the file (the edit button)
4. Make the changes in the file
5. Scroll to the bottom of the page, select the "Create a new branch for this commit and start a pull request" option, and then click "Propose file change".
6. Follow the directions!

Once the PR is open, we can make some comments. You might have to change a few things, but you can do that through the web-interface as well. Good luck!

p.s., if you want to know how to submit a PR using Git, the JuMP [contributing guide](https://github.com/JuliaOpt/JuMP.jl/blob/master/CONTRIBUTING.md#contribute-code-to-jump) has a list of tutorials where you can learn.
