### ISSUE TITLE
Finalizer for Env

### ISSUE THREAD

**Issue by joehuchette** [jump-dev/Gurobi.jl#24]
Eli complained today about memory becoming saturated with a (small) model in a tight loop. I thought this was fixed when we changed the behavior in CPLEX.jl, but it doesn't look like it. 

cc @mlubin @IainNZ

**Comment by mlubin** [comment]
Can we close this?

**Comment by joehuchette** [comment]
I don't think I ever got a test case from Eli, but presumably whatever potential issue there was hasn't been fixed.
