### ISSUE TITLE
connect to remote Gurobi server

### ISSUE THREAD

**Issue by tramelon** [jump-dev/Gurobi.jl#253]
How can I connect to a remote Gurobi server using Host IP/Name and password?

**Comment by odow** [comment]
This feature is not implemented yet. See https://github.com/JuliaOpt/Gurobi.jl/pull/54.

Although [this comment](https://github.com/JuliaOpt/Gurobi.jl/pull/54#issuecomment-362085156) suggests that you can get it to work with the correct license.

Note that the Julia wrapper is maintained by volunteers and is not officially supported by Gurobi. If you are a paid Gurobi customer, you should contact them for support.

**Comment by odow** [comment]
Gurobi.jl now wraps the complete C API. You can use the C API to create a remote environment, and then pass this to `Gurobi.Optimizer` with `Gurobi.Optimizer(env)`.
