### ISSUE TITLE
Compute server connection not closed properly after "ctrl+c"

### ISSUE THREAD

**Issue by ohmsweetohm1** [jump-dev/Gurobi.jl#320]
Interrupting a julia program with "ctrl+c", that has an open connection to a Gurobi compute server results in an still open connection.
If a "normal" error occurs and the julia program is interrupted there is no such problem.   
Maybe somewhere an `InterruptException` should be handled. :)

**Comment by odow** [comment]
See also: https://github.com/JuliaOpt/Gurobi.jl/issues/52

Handling CTRL+C at all would be an improvement, regardless of the compute server.

**Comment by odow** [comment]
Closing as duplicate of #52
