### ISSUE TITLE
Error in set_start_value with BilevelJuMP

### ISSUE THREAD

**Issue by davide-f** [jump-dev/Gurobi.jl#339]
Hi,

I am experiencing an annoying error when using BilevelJuMP with Gurobi Solver; no error occur with IpOpt instead.
The error code is:
In `MathOptInterface.ScalarAffineFunction{Float64}`-in-`MathOptInterface.GreaterThan{Float64}` constraint: Constant -2.0 of the function is not zero. The function constant should be moved to the set. You can use `MOI.Utilities.normalize_and_add_constraint` which does this automatically.

A sample code that reproduces the issue is attached below.
Developers of MathOptInterface and BilevelJuMP are adviced as well.

Thank you very much
[report_error.txt](https://github.com/jump-dev/Gurobi.jl/files/4893681/report_error.txt)

**Comment by odow** [comment]
This is an issue with BilevelJuMP, not Gurobi.jl. You should open an issue there.
