### ISSUE TITLE
Problems with Gurobi & JuMP

### ISSUE THREAD

**Issue by guillermoCabrera** [jump-dev/Gurobi.jl#340]
Hi,

I installed Gurobi 9.02 on Ubuntu 20.04. Gurobi works perfectly fine. Then, I installed Julia and JuMP. Julia finds both the Gurobi_Home and the LD_LIBRARY_PATH environment variables. However, when trying to run Gurobi with JuMP I've got the following error message:

Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /home/guillermo/.julia/packages/Gurobi/7YNJV/deps/build.jl:154
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1044
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:392
│  [7] top-level scope at none:0
│ in expression starting at /home/guillermo/.julia/packages/Gurobi/7YNJV/deps/build.jl:152
│ Unable to locate Gurobi installation. Running some common diagnostics.
│ 
│ Gurobi.jl only supports the following versions:
│ 
│  - gurobi90
│  - gurobi81
│  - gurobi80
│  - gurobi75
│  - gurobi70
│ 
│ Did you download and install one of these versions from gurobi.com?
│ 
│ 
│ Found GUROBI_HOME =  /home/guillermo/opt/gurobi902/linux64
│ 
│ Does this point to the correct install location?
│ - on Windows, this might be `C:\Program Files\gurobi810\win64\`
│ - alternatively, on Windows, this might be `C:/Program Files/gurobi810/win64/`
│ - on OSX, this might be `/Library/gurobi810/mac64/`
│ - on Unix, this might be `/home/my_user/gurobi810/linux64/`
│ 
│ Note: this has to be a full path, not a path relative to your current
│ directory or your home directory.
│ 
│ We're going to look for the Gurobi library in this directory:
│     /home/guillermo/opt/gurobi902/linux64/lib
│ 
│ That directory has the following files:
│ 
│  - /home/guillermo/opt/gurobi902/linux64/lib/gurobi-javadoc.jar
│  - /home/guillermo/opt/gurobi902/linux64/lib/gurobi.jar
│  - /home/guillermo/opt/gurobi902/linux64/lib/gurobi.py
│  - /home/guillermo/opt/gurobi902/linux64/lib/gurobi90.netstandard20.dll
│  - /home/guillermo/opt/gurobi902/linux64/lib/gurobi90.netstandard20.xml
│  - /home/guillermo/opt/gurobi902/linux64/lib/libGurobiJni90.so
│  - /home/guillermo/opt/gurobi902/linux64/lib/libgurobi.so.9.0.2
│  - /home/guillermo/opt/gurobi902/linux64/lib/libgurobi90.so
│  - /home/guillermo/opt/gurobi902/linux64/lib/libgurobi90_light.so
│  - /home/guillermo/opt/gurobi902/linux64/lib/libgurobi_c++.a
│  - /home/guillermo/opt/gurobi902/linux64/lib/libgurobi_g++4.2.a
│  - /home/guillermo/opt/gurobi902/linux64/lib/libgurobi_g++5.2.a
│  - /home/guillermo/opt/gurobi902/linux64/lib/python2.7_utf16
│  - /home/guillermo/opt/gurobi902/linux64/lib/python2.7_utf32
│  - /home/guillermo/opt/gurobi902/linux64/lib/python3.5_utf32
│  - /home/guillermo/opt/gurobi902/linux64/lib/python3.6_utf32
│  - /home/guillermo/opt/gurobi902/linux64/lib/python3.7
│  - /home/guillermo/opt/gurobi902/linux64/lib/python3.7_utf32
│  - /home/guillermo/opt/gurobi902/linux64/lib/python3.8_utf32
│  - /home/guillermo/opt/gurobi902/linux64/lib/rootcert.pem
│ 
│ We were looking for (but could not find) a file named like
│ `libgurobiXXX.so`, `libgurobiXXX.dylib`, or `gurobiXXX.dll`. You
│ should update your GUROBI_HOME environment variable to point to the
│ correct location.

Any idea what's going on?

**Comment by odow** [comment]
Super weird. What's the output of:

```Julia
using Libdl
Libdl.dlopen("/home/guillermo/opt/gurobi902/linux64/lib/libgurobi90.so")
```

**Comment by guillermoCabrera** [comment]
Hi Oscar,

This is the output:

ERROR: could not load library "/home/guillermo/opt/gurobi902/linux64/lib/libgurobi90.so"
/home/guillermo/opt/gurobi902/linux64/lib/libgurobi90.so: wrong ELF class: ELFCLASS64
Stacktrace:
 [1] dlopen(::String, ::UInt32) at /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.0/Libdl/src/Libdl.jl:97 (repeats 2 times)
 [2] top-level scope at none:0

julia> Libdl.dlopen("/home/guillermo/opt/gurobi902/linux64/lib/libgurobi90.so")
ERROR: could not load library "/home/guillermo/opt/gurobi902/linux64/lib/libgurobi90.so"
/home/guillermo/opt/gurobi902/linux64/lib/libgurobi90.so: wrong ELF class: ELFCLASS64
Stacktrace:
 [1] dlopen(::String, ::UInt32) at /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.0/Libdl/src/Libdl.jl:97 (repeats 2 times)
 [2] top-level scope at none:0

**Comment by odow** [comment]
Looks like you have 32-bit Julia. You need to use the 64-bit one.

**Comment by guillermoCabrera** [comment]
mmmm that's weird..... I installed the julia-1.4.2-linux-x86_64.tar.gz file I downloaded from the Julia's website.....

**Comment by odow** [comment]
You sure you're using that binary then? And not a different 32 bit one you have lying around?

**Comment by guillermoCabrera** [comment]
Pretty sure. Actually, Julia was one of the first programs I installed after formatting my computer, so only the 64 bit file was in my Download folder. 

Anyway, I decided to uninstall Julia and then install it again from terminal (sudo apt-get install julia). This worked fine.  
Thanks for your help!
Guillermo
