### ISSUE TITLE
Generating a simple problem that reliably triggers hits :UserLimit

### ISSUE THREAD

**Issue by vtjeng** [jump-dev/Gurobi.jl#342]
I'm on Julia 1.4 but using an older version of the JuMP and Gurobi packages (I'm planning to upgrade soon, but one of my other packages constrains me to using JuMP v0.18.6.):

```
  [2e9cd046] Gurobi v0.8.1
  [4076af6c] JuMP v0.18.6
```

When solving an MILP via JuMP using the `GurobiSolver`, I've found that `getobjbound` appears to ignore any constant term (perhaps related to [this issue](https://github.com/jump-dev/Gurobi.jl/issues/111)) if the objective is a `JuMP.AffExpr` when my solve hits a `:UserLimit`. I haven't been able to confirm whether this is an issue if a) my solve does not hit a `:UserLimit` or b) for `getobjectivevalue`. (I can get around this issue by adding an additional variable constrained to be equal to the objective and optimizing over the variable instead.) 

I wanted to add a test (although I'm still not sure which package that test should go into) to ensure that this is no longer the case, but I haven't been able to reproduce this with a simple example as I can't figure out how to reliably trigger `:UserLimit` with a small problem. Does anyone have a suggestion for a problem that is simple to understand but for which I can get the `:UserLimit` status?

**Comment by odow** [comment]
You could do something like: https://github.com/jump-dev/Gurobi.jl/blob/183a1c5916ff6253193e7242eba48a172ea7365f/test/MOI/MOI_callbacks.jl#L27-L53

but set a time limit of 0 seconds or a solution limit of 1 or something.

**Comment by vtjeng** [comment]
For users who simply want to trigger a particular termination status from the optimizer for testing purposes (but are not interested in it being a `Gurobi.Optimizer` in particular), you can use the suggestion by @mlubin [here](https://discourse.julialang.org/t/testing-code-that-is-executed-when-solve-reaches-non-optimal-status/47293/4).
