### ISSUE TITLE
Failure installing Gurobi Package Julia 1.0.2

### ISSUE THREAD

**Issue by LailaZahran** [jump-dev/Gurobi.jl#356]
My versioninfo() :

```
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

Installed Gurobi Version 9.0.3
and did the following commands for its installation in Julia 

ENV["GUROBI_HOME"] = "/Library/gurobi903/mac64"
import Pkg
Pkg.add("Gurobi")
Pkg.build("Gurobi")

The path is correct and the Gurobi I have is v0.5.6

However I get the following error when building it, so how can I fix it? I tried also Pkg.build("Gurobi") but no gain..
```

┌ Error: Error building `Gurobi`: 
│ ERROR: LoadError: Unable to locate Gurobi installation. Note that this must be downloaded separately from gurobi.com
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /Users/lailazahran/.julia/packages/Gurobi/kaIvm/deps/build.jl:50
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1044
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:392
│  [7] top-level scope at none:0
│ in expression starting at /Users/lailazahran/.julia/packages/Gurobi/kaIvm/deps/build.jl:49
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097
```

**Comment by odow** [comment]
You need to upgrade to the latest version of Gurobi.jl.

Try `] add Gurobi@0.8`, then remove any package that are blocking you from updating.

**Comment by odow** [comment]
Closing since this is not an issue with Gurobi.jl. The user has an old package version that does not support Gurobi 9. Please post on https://discourse.julialang.org/c/domain/opt/13 if you have further questions.
