### ISSUE TITLE
Error trying to build in Jupyter Notebook on Mac OS Catalina

### ISSUE THREAD

**Issue by miles-frankllin** [jump-dev/Gurobi.jl#361]
```Julia
# Ran the following 
ENV["GUROBI_HOME"] = "/Library/gurobi902/mac64/"
import Pkg
Pkg.add("Gurobi")
Pkg.build("Gurobi")

==================================================

Updating registry at `~/.julia/registries/General`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
   Building Gurobi → `~/.julia/packages/Gurobi/LtWGf/deps/build.log`
┌ Error: Error building `Gurobi`: 
│ ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
│ open an issue at https://github.com/jump-dev/Gurobi.jl and post the full
│ print-out of this diagnostic attempt.
│ 
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /Users/milesfranklin/.julia/packages/Gurobi/LtWGf/deps/build.jl:153
│  [3] include(::String) at ./client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at /Users/milesfranklin/.julia/packages/Gurobi/LtWGf/deps/build.jl:151
│ 
│ **Unable to locate Gurobi installation. Running some common diagnostics.**
│ 
│ Gurobi.jl only supports the following versions:
│ 
│  - gurobi90
│ 
│ Did you download and install one of these versions from gurobi.com?
│ 
│ Found GUROBI_HOME =  /Library/gurobi902/mac64/
│ 
│ Does this point to the correct install location?
│ 
│ We're going to look for the Gurobi library in this directory:
│     /Library/gurobi902/mac64/lib
│ 
│ That directory has the following files:
│ 
│ Aha! We tried looking in `/Library/gurobi902/mac64/lib`, but something went wrong. Are
│ you sure that your GUROBI_HOME environment variable is correct?
│ When combined with the appropriate suffix (e.g., `lib` or
│ `bin`, it needs to point to a valid directory.
│ 
│ 
│ You should set the `GUROBI_HOME` environment variable to point to the
│ install location then try again. For example (updating the path to the
│ correct location if needed):
│ ```
│ # On Windows, this might be
│ ENV["GUROBI_HOME"] = "C:\\Program Files\\gurobi902\\win64\\"
│ import Pkg
│ Pkg.add("Gurobi")
│ Pkg.build("Gurobi")
│ 
│ # On OSX, this might be
│ ENV["GUROBI_HOME"] = "/Library/gurobi902/mac64/"
│ import Pkg
│ Pkg.add("Gurobi")
│ Pkg.build("Gurobi")
│ 
│ # On Unix, this might be
│ ENV["GUROBI_HOME"] = "/opt/gurobi902/linux64/"
│ import Pkg
│ Pkg.add("Gurobi")
│ Pkg.build("Gurobi")
│ ```
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949
```

**Comment by odow** [comment]
Per the error message:

> Aha! We tried looking in `/Library/gurobi902/mac64/lib`, but something went wrong. Are
> you sure that your GUROBI_HOME environment variable is correct?
> When combined with the appropriate suffix (e.g., `lib` or
> `bin`, it needs to point to a valid directory.

You need to set the `GUROBI_HOME` environment variable to point to the place you actually installed Gurobi. `/Library/gurobi902/mac64/` is just an example.

**Comment by miles-frankllin** [comment]
Thank you! I installed from within a Jupyter Notebook so should /Users/milesfranklin/.julia/packages/Gurobi be the appropriate path or just /Users/milesfranklin/.julia/packages?

**Comment by odow** [comment]
No. 

> Did you download and install one of these versions from gurobi.com?

It needs to be the location that you installed the official Gurobi binary to.

**Comment by miles-frankllin** [comment]
I ran the a mini Python script below and didn't find anything... weird. I'm stepping away from my laptop now but try reinstalling first and get back to you. 

`
import os

for root, dirs, files in os.walk("/Users/milesfranklin/Library"):
	for name in files:
		if "gurobi" in name:
			print(os.path.join(root, name))
	for name in dirs:
		if "gurobi" in name:
			print(os.path.join(root, name))
`

**Comment by odow** [comment]
It will be in `/Library`, not `~/Library`.

**Comment by miles-frankllin** [comment]
I didn't realize that I need a license, so I have put in a request for that as well. I will likely be away from this until Monday. Thank you and enjoy the weekend.

**Comment by odow** [comment]
Closing as stale. Please re-open if you still have issues after obtaining a license and setting `GUROBI_HOME` as appropriate.

Here's the relevant Gurobi documentation: https://www.gurobi.com/documentation/9.0/quickstart_mac/software_installation_guid.html
