### ISSUE TITLE
Accessing the presolved model

### ISSUE THREAD

**Issue by gdragotto** [jump-dev/Gurobi.jl#366]
Hey,

I'm trying to access to the presolved model given a raw user-input model.

```set_optimizer_attribute(model, "Presolve", 1)
optimize!(model)

BaseGurobiModel = JuMP.backend(model) 
PresolvedGurobiModel = Ptr{Ptr{GRBmodel}}()

test=GRBpresolvemodel(BaseGurobiModel,PresolvedGurobiModel)

display(BaseGurobiModel)
display(PresolvedGurobiModel)
display(test)
```

The result is:

```sense  : minimize
    number of variables             = 2
    number of linear constraints    = 3
    number of quadratic constraints = 0
    number of sos constraints       = 0
    number of non-zero coeffs       = 4
    number of non-zero qp objective terms  = 0
    number of non-zero qp constraint terms = 0
Ptr{Ptr{Nothing}} @0x0000000000000000
10003 #The code for GRB_ERROR_INVALID_ARGUMENT 
````

So, in short, I get GRB_ERROR_INVALID_ARGUMENT. Should the PresolvedGurobiModel object be filled with an empty model pointer? 
I'm sure there is some typing convention that I'm missing. This is the function header for GRBpresolvemodel:

```function GRBpresolvemodel(model, presolvedP)
    ccall((:GRBpresolvemodel, libgurobi), Cint, (Ptr{GRBmodel}, Ptr{Ptr{GRBmodel}}), model, presolvedP)
end
```
I understand that there is an implicit way to cast the first argument to _Ptr{GRBmodel}_, but apparently there is none to _Ptr{Ptr{GRBmodel}}_.

Thank you

**Comment by mtanneau** [comment]
Can you provide a MWE with what's _before_ the call to `optimize!`?

Depending on whether you're using direct mode or not, the type of `BaseGurobiModel` will be affected.
By default, `backend(model)` will be a JuMP-level object that caches the model. In direct mode, it will be a `Gurobi.Optimizer`.

In any case, you cannot pass it to `GRBpresolvemodel` directly, you would need to dig between layers a little more.

**Comment by gdragotto** [comment]
So, skipping the instance-specific stuff, the `model` object is built as a _direct_model_ with

`model = direct_model(Gurobi.Optimizer())`

**Comment by mtanneau** [comment]
This seems to do the trick:

```julia
import Gurobi
using JuMP

_env = Ref{Ptr{Cvoid}}()
ret = Gurobi.GRBloadenv(_env, C_NULL)
GRBENV = _env[]  # The Gurobi environment

# Create the model with JuMP
model = direct_model(Gurobi.Optimizer())
@variable(model, x >= 0)
@objective(model, Min, x)
optimize!(model)

# Access the MOI layer
grb_moi = backend(model)

# Access the Gurobi layer
grb = grb_moi.inner

# Retrieve a pointer to the presolved model
_grb_presolved = Ref{Ptr{Cvoid}}()
ret = Gurobi.GRBpresolvemodel(grb, _grb_presolved)
Gurobi._check_ret(GRBENV, ret)  # sanity check
@show ret  # Should be 0
grb_presolved = _grb_presolved[]  # You must de-reference the pointer!

# Query the number of variables in presolved model
_nvar = Ref{Cint}()
ret = Gurobi.GRBgetintattr(grb_presolved, "NumVars", _nvar)
Gurobi._check_ret(GRBENV, ret)  # sanity check
nvar = _nvar[]

@show nvar
```

FYI, the `GRBpresolvemodel` also performs presolve, so it should be possible to do without the call to `optimize!`.
I think it would require a manual update of the model though, which would need to be triggered at the MOI level, i.e., on `grb_moi`.

**Comment by gdragotto** [comment]
With some help from @mtanneau and the Gurobi Doc, there is a quick way. First, I forgot to disable the _DualReductions_. Then, the call is as follow

```
model = direct_model(Gurobi.Optimizer())
set_optimizer_attribute(model, "Presolve", 1)
set_optimizer_attribute(model, "DualReductions", 0)

BaseGurobiModel = JuMP.backend(model) 
_pr = Ref{Ptr{Cvoid}}()

test=GRBpresolvemodel(BaseGurobiModel,_pr)
PresolvedGurobiModel= _pr[]



```

**Comment by odow** [comment]
One extra note, instead of passing the environment pointer around, you can just pass an instance of `Gurobi.Env()`, which will manage the finalizer, etc.
