### ISSUE TITLE
[GUROBI 9.1.0] - UndefVarError: model not defined

### ISSUE THREAD

**Issue by JeanjoCarlos** [jump-dev/Gurobi.jl#371]
Hi!

With the Gurobi update my code is no longer working. I'm trying to solve a quadratic problem, but apparently the way to build the model seems to have changed. Can someone help me?

```Julia
env = Gurobi.Env()

        # solve using Barrier
        setparam!(env, "Method", 2)
        setparam!(env, "OutputFlag", 0)

         # construct the model
         model = gurobi_model(env;
             name = "qp_primal",
             H = Matrix{Float64}(I, n, n),
             f = -x,
             A = α, #matriz de restrições
             b = β) #vetor b, de demanda

        # run optimization
        optimize(model)

        flag=get_status(model)

        if (flag==:optimal)
            sol = get_solution(model)
            return sol
        else
            sol = "ERRO!"
            return sol
        end
```

**Comment by odow** [comment]
Read this: https://discourse.julialang.org/t/ann-upcoming-breaking-changes-to-cplex-jl-and-gurobi-jl

The error message you will have got when running `setparam!` also contains an explanation:
```Julia
julia> using Gurobi

julia> env = Gurobi.Env()

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

Academic license - for non-commercial use only - expires 2020-12-05
Gurobi.Env(Ptr{Nothing} @0x00007fdfb04d9000, false, 0)

julia> setparam!(env, "Method", 2)
ERROR: The C API of Gurobi.jl has been rewritten to expose the complete C API, and
all old functions have been removed. For more information, see the Discourse
announcement: https://discourse.julialang.org/t/ann-upcoming-breaking-changes-to-cplex-jl-and-gurobi-jl

Here is a brief summary of the changes.

* Constants have changed. For example `CB_MIPNODE` is now `GRB_CB_MIPNODE`
    to match the C API.
* Function names have changed. For example `free_env(env)` is now
    `GRBfreeenv(env)`.
* For users of `Gurobi.Optimizer()`, `model.inner` is now a pointer to the C
    model, instead of a `Gurobi.Model` object. However, conversion means that
    you should always pass `model` instead of `model.inner` to the low-level
    functions. For example:
    ```julia
    model = direct_model(Gurobi.Optimizer())
    grb_model = backend(model)  # grb_model is Gurobi.Optimizer
    # Old
    Gurobi.tune_model(grb_model.inner)
    # New
    GRBtunemodel(grb_model)
    ```
* Some functions have been removed entirely. For example:
    ```julia
    using JuMP, Gurobi
    model = direct_model(Gurobi.Optimizer())
    optimize!(model)
    grb_model = backend(model)
    stat = Gurobi.get_status_code(grb_model.inner)
    ```
    is now:
    ```julia
    using JuMP, Gurobi
    model = direct_model(Gurobi.Optimizer())
    optimize!(model)
    valueP = Ref{Cint}()
    grb_model = backend(model)
    ret = GRBgetintattr(grb_model, "Status", valueP)
    if ret != 0
        # Do something because the call failed
    end
    stat = valueP[]
    ```

The new API is more verbose, but the names and function arguments are now
identical to the C API, documentation for which is available at:
https://www.gurobi.com/documentation/9.0/refman/c_api_details.html

To revert to the old API, use:

    import Pkg
    Pkg.add(Pkg.PackageSpec(name = "Gurobi", version = v"0.8.1"))

Then restart Julia for the change to take effect.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] setparam!(::Gurobi.Env, ::Vararg{Any,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/oscar/.julia/dev/Gurobi/src/deprecated_functions.jl:524
 [3] setparam!(::Gurobi.Env, ::Vararg{Any,N} where N) at /Users/oscar/.julia/dev/Gurobi/src/deprecated_functions.jl:524
 [4] top-level scope at REPL[9]:1
```

Either use the older version of Gurobi.jl, update your code, or use JuMP.

**Comment by JeanjoCarlos** [comment]
I'm already using JuMP but I can't go back to the old configuration, due to the laboratory's policy. What I need to know is what parts I need to modify and what I need to modify it for ... I am not familiar with the new syntax for High-level Quadratic Programming API. Can you please help me?

**Comment by odow** [comment]
> I am not familiar with the new syntax for High-level Quadratic Programming API

`gurobi_model` has been removed from Gurobi.jl. You would need to use the low-level C API. For example, adapted from: https://www.gurobi.com/documentation/9.1/examples/qp_c_c.html

I highly recommend you use JuMP instead, with something like:
```Julia
using JuMP
using Gurobi
model = Model(Gurobi.Optimizer)
@variable(model, x[1:2])
@objective(model, Min, x' * H * x + f' * x)
@constraint(model, A * x .<= b)
optimize!(model)
```

**Comment by odow** [comment]
Closing because there doesn't seem to be anything to do on the Gurobi.jl side.
