### ISSUE TITLE
Gurobi not properly installed. 

### ISSUE THREAD

**Issue by zendevil** [jump-dev/Gurobi.jl#376]
I want to use Gurobi in a program like so:

```
using Gurobi
```

To which get the following error message:

```
ERROR: LoadError:     Gurobi not properly installed. Please run Pkg.build("Gurobi"). For
    more information go to https://github.com/jump-dev/Gurobi.jl

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at /Users/prikshetsharma/.julia/packages/Gurobi/P6eVP/src/Gurobi.jl:7
 [3] include(::Function, ::Module, ::String) at ./Base.jl:380
 [4] include(::Module, ::String) at ./Base.jl:368
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:331 [inlined]
 [7] eval(::Expr) at ./client.jl:467
 [8] top-level scope at ./none:3
in expression starting at /Users/prikshetsharma/.julia/packages/Gurobi/P6eVP/src/Gurobi.jl:4
ERROR: LoadError: Failed to precompile Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b] to /Users/prikshetsharma/.julia/compiled/v1.5/Gurobi/do9v6_rMyJO.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
 [6] include(::Function, ::Module, ::String) at ./Base.jl:380
 [7] include(::Module, ::String) at ./Base.jl:368
 [8] exec_options(::Base.JLOptions) at ./client.jl:296
 [9] _start() at ./client.jl:506
in expression starting at /Users/prikshetsharma/Documents/clotorch/src/clotorch/flight/opt.jl:

```

When installing Gurobi itself, I get the following error, mentioning a problem with installation and steps to remedy it:

```
Pkg.build("Gurobi")
   Building Gurobi → `~/.julia/packages/Gurobi/P6eVP/deps/build.log`
┌ Error: Error building `Gurobi`: 
│ ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
│ open an issue at https://github.com/jump-dev/Gurobi.jl and post the full
│ print-out of this diagnostic attempt.
│ 
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /Users/prikshetsharma/.julia/packages/Gurobi/P6eVP/deps/build.jl:161
│  [3] include(::String) at ./client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at /Users/prikshetsharma/.julia/packages/Gurobi/P6eVP/deps/build.jl:155
│ 
│ **Unable to locate Gurobi installation. Running some common diagnostics.**
│ 
│ Gurobi.jl only supports the following versions:
│ 
│  - gurobi90
│  - gurobi91
│ 
│ Did you download and install one of these versions from gurobi.com?
│ Installing Gurobi.jl via the Julia package manager is _not_ sufficient!
│ 
│ Found GUROBI_HOME =  /Library/gurobi910/mac64/
│ 
│ Does this point to the correct install location?
│ 
│ We're going to look for the Gurobi library in this directory:
│     /Library/gurobi910/mac64/lib
│ 
│ That directory has the following files:
│ 
│ Aha! We tried looking in `/Library/gurobi910/mac64/lib`, but something went wrong. Are
│ you sure that your GUROBI_HOME environment variable is correct?
│ When combined with the appropriate suffix (e.g., `lib` or
│ `bin`, it needs to point to a valid directory.
│ 
│ 
│ You should set the `GUROBI_HOME` environment variable to point to the
│ install location then try again. For example (updating the path to the
│ correct location if needed):
│ ```
│ # On Windows, this might be
│ ENV["GUROBI_HOME"] = "C:\\Program Files\\gurobi910\\win64\\"
│ import Pkg
│ Pkg.add("Gurobi"
│ Pkg.build("Gurobi")
│ 
│ # On OSX, this might be
│ ENV["GUROBI_HOME"] = "/Library/gurobi910/mac64/"
│ import Pkg
│ Pkg.add("Gurobi")
│ Pkg.build("Gurobi")
│ 
│ # On Unix, this might be
│ ENV["GUROBI_HOME"] = "/opt/gurobi910/linux64/"
│ import Pkg
│ Pkg.add("Gurobi")
│ Pkg.build("Gurobi")
│ ```
│ **Note: your path may differ. Check which folder you installed the Gurobi
│ binary in, and update the path accordingly.**
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949


```

I've already following the steps mentioned for macOS in the above trace, but I still get the above error. How to install Gurobi and use it successfully?

**Comment by blegat** [comment]
Can you give the output you obtain by runniingf `ls /Library/gurobi910/mac64/lib` and `ls /Library/gurobi910/mac64` from the terminal ?

**Comment by odow** [comment]
It looks like the path `/Library/gurobi910/mac64` doesn't exist. You need to find the actual path you installed Gurobi into and set the `GUROBI_HOME` environment variable appropriately. For example, if you installed Gurobi 9.0.2, the path might be `/Library/gurobi902/mac64`.

**Comment by odow** [comment]
Closing as stale. Please re-open if the above instructions did not work.

**Comment by GaiusJ** [comment]
i am getting a similar error
i installed gurobi into C:

its kinda confusiing for me to see he is looking for an file that is in this directory but he cant find it

Error building `Gurobi`: 
ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
open an issue at https://github.com/jump-dev/Gurobi.jl and post the full
print-out of this diagnostic attempt.

Stacktrace:
 [1] error(s::String)
   path
 [2] top-level scope
   path
 [3] include(fname::String)
   path
 [4] top-level scope
   @ none:5
in expression starting at [C:\Users\juliu\.julia\packages\Gurobi\BAtIN\deps\build.jl:159](file:///path

**Unable to locate Gurobi installation. Running some common diagnostics.**

Gurobi.jl only supports the following versions:

 - gurobi91
 - gurobi90

Did you download and install one of these versions from gurobi.com?
Installing Gurobi.jl via the Julia package manager is _not_ sufficient!

Found GUROBI_HOME =  [C:\gurobi1002\win64\](file:///C:/gurobi1002/win64/)

Does this point to the correct install location?

We're going to look for the Gurobi library in this directory:
    [C:\gurobi1002\win64\bin](file:///C:/gurobi1002/win64/bin)

That directory has the following files:

 - [C:\gurobi1002\win64\bin\Gurobi100.NET.XML](file:///C:/gurobi1002/win64/bin/Gurobi100.NET.XML)
 - [C:\gurobi1002\win64\bin\Gurobi100.NET.dll](file:///C:/gurobi1002/win64/bin/Gurobi100.NET.dll)
 - [C:\gurobi1002\win64\bin\GurobiJni100.dll](file:///C:/gurobi1002/win64/bin/GurobiJni100.dll)
 - [C:\gurobi1002\win64\bin\grb_ts.exe](file:///C:/gurobi1002/win64/bin/grb_ts.exe)
 - [C:\gurobi1002\win64\bin\grbcluster.exe](file:///C:/gurobi1002/win64/bin/grbcluster.exe)
 - [C:\gurobi1002\win64\bin\grbgetkey.exe](file:///C:/gurobi1002/win64/bin/grbgetkey.exe)
 - [C:\gurobi1002\win64\bin\grbprobe.exe](file:///C:/gurobi1002/win64/bin/grbprobe.exe)
 - [C:\gurobi1002\win64\bin\grbtune.exe](file:///C:/gurobi1002/win64/bin/grbtune.exe)
 - [C:\gurobi1002\win64\bin\gurobi.bat](file:///C:/gurobi1002/win64/bin/gurobi.bat)
 - [C:\gurobi1002\win64\bin\gurobi100.dll](file:///C:/gurobi1002/win64/bin/gurobi100.dll)
 - [C:\gurobi1002\win64\bin\gurobi100.netstandard20.dll](file:///C:/gurobi1002/win64/bin/gurobi100.netstandard20.dll)
 - [C:\gurobi1002\win64\bin\gurobi100_light.dll](file:///C:/gurobi1002/win64/bin/gurobi100_light.dll)
 - [C:\gurobi1002\win64\bin\gurobi_cl.exe](file:///C:/gurobi1002/win64/bin/gurobi_cl.exe)
 - [C:\gurobi1002\win64\bin\vslauncher.exe](file:///C:/gurobi1002/win64/bin/vslauncher.exe)
 - [C:\gurobi1002\win64\bin\vswhere.exe](file:///C:/gurobi1002/win64/bin/vswhere.exe)

We were looking for (but could not find) a file named like
`libgurobiXXX.so`, `libgurobiXXX.dylib`, or `gurobiXXX.dll`.


You should set the `GUROBI_HOME` environment variable to point to the
install location then try again. For example (updating the path to the
correct location if needed):
```
# On Windows, this might be
ENV["GUROBI_HOME"] = "C:\\Program Files\\gurobi910\\win64\\"
import Pkg
Pkg.add("Gurobi")
Pkg.build("Gurobi")

# On OSX, this might be
ENV["GUROBI_HOME"] = "/Library/gurobi910/mac64/"
import Pkg
Pkg.add("Gurobi")
Pkg.build("Gurobi")

# On Unix, this might be
ENV["GUROBI_HOME"] = "/opt/gurobi910/linux64/"
import Pkg
Pkg.add("Gurobi")
Pkg.build("Gurobi")
```
**Note: your path may differ. Check which folder you installed the Gurobi
binary in, and update the path accordingly.**


Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\Types.jl:67](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/Types.jl:67)
  [2] (::Pkg.Operations.var"#66#73"{Bool, Pkg.Types.Context, String, Pkg.Types.PackageSpec, String})()
    @ Pkg.Operations [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\Operations.jl:1060](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1060)
  [3] withenv(::Pkg.Operations.var"#66#73"{Bool, Pkg.Types.Context, String, Pkg.Types.PackageSpec, String}, ::Pair{String, String}, ::Vararg{Pair{String}})
    @ Base [.\env.jl:172](https://file+.vscode-resource.vscode-cdn.net/e%3A/Uni/Bachelor/Sem6/POM%20Cases/env.jl:172)
  [4] (::Pkg.Operations.var"#107#112"{String, Bool, Bool, Bool, Pkg.Operations.var"#66#73"{Bool, Pkg.Types.Context, String, Pkg.Types.PackageSpec, String}, Pkg.Types.PackageSpec})()
    @ Pkg.Operations [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\Operations.jl:1619](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1619)
  [5] with_temp_env(fn::Pkg.Operations.var"#107#112"{String, Bool, Bool, Bool, Pkg.Operations.var"#66#73"{Bool, Pkg.Types.Context, String, Pkg.Types.PackageSpec, String}, Pkg.Types.PackageSpec}, temp_env::String)
    @ Pkg.Operations [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\Operations.jl:1493](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1493)
  [6] (::Pkg.Operations.var"#105#110"{Dict{String, Any}, Bool, Bool, Bool, Pkg.Operations.var"#66#73"{Bool, Pkg.Types.Context, String, Pkg.Types.PackageSpec, String}, Pkg.Types.Context, Pkg.Types.PackageSpec, String, Pkg.Types.Project, String})(tmp::String)
    @ Pkg.Operations [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\Operations.jl:1582](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1582)
  [7] mktempdir(fn::Pkg.Operations.var"#105#110"{Dict{String, Any}, Bool, Bool, Bool, Pkg.Operations.var"#66#73"{Bool, Pkg.Types.Context, String, Pkg.Types.PackageSpec, String}, Pkg.Types.Context, Pkg.Types.PackageSpec, String, Pkg.Types.Project, String}, parent::String; prefix::String)
    @ Base.Filesystem [.\file.jl:764](https://file+.vscode-resource.vscode-cdn.net/e%3A/Uni/Bachelor/Sem6/POM%20Cases/file.jl:764)
  [8] mktempdir(fn::Function, parent::String) (repeats 2 times)
    @ Base.Filesystem [.\file.jl:760](https://file+.vscode-resource.vscode-cdn.net/e%3A/Uni/Bachelor/Sem6/POM%20Cases/file.jl:760)
  [9] sandbox(fn::Function, ctx::Pkg.Types.Context, target::Pkg.Types.PackageSpec, target_path::String, sandbox_path::String, sandbox_project_override::Pkg.Types.Project; preferences::Dict{String, Any}, force_latest_compatible_version::Bool, allow_earlier_backwards_compatible_versions::Bool, allow_reresolve::Bool)
    @ Pkg.Operations [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\Operations.jl:1540](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1540)
 [10] build_versions(ctx::Pkg.Types.Context, uuids::Set{Base.UUID}; verbose::Bool)
    @ Pkg.Operations [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\Operations.jl:1041](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1041)
 [11] build(ctx::Pkg.Types.Context, uuids::Set{Base.UUID}, verbose::Bool)
    @ Pkg.Operations [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\Operations.jl:898](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:898)
 [12] build(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; verbose::Bool, kwargs::Base.Pairs{Symbol, VSCodeServer.IJuliaCore.IJuliaStdio{Base.PipeEndpoint, typeof(VSCodeServer.io_send_callback)}, Tuple{Symbol}, NamedTuple{(:io,), Tuple{VSCodeServer.IJuliaCore.IJuliaStdio{Base.PipeEndpoint, typeof(VSCodeServer.io_send_callback)}}}})
    @ Pkg.API [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\API.jl:1029](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/API.jl:1029)
 [13] build(pkgs::Vector{Pkg.Types.PackageSpec}; io::VSCodeServer.IJuliaCore.IJuliaStdio{Base.PipeEndpoint, typeof(VSCodeServer.io_send_callback)}, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\API.jl:156](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/API.jl:156)
 [14] build(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\API.jl:145](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/API.jl:145)
 [15] #build#99
    @ [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\API.jl:144](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/API.jl:144) [inlined]
 [16] build
    @ [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\API.jl:144](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/API.jl:144) [inlined]
 [17] #build#98
    @ [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\API.jl:143](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/API.jl:143) [inlined]
 [18] build(pkg::String)
    @ Pkg.API [C:\Users\juliu\AppData\Local\Programs\Julia-1.8.3\share\julia\stdlib\v1.8\Pkg\src\API.jl:143](file:///C:/Users/juliu/AppData/Local/Programs/Julia-1.8.3/share/julia/stdlib/v1.8/Pkg/src/API.jl:143)
 [19] top-level scope
    @ [e:\Uni\Bachelor\Sem6\POM](file:///E:/Uni/Bachelor/Sem6/POM) Cases\new.ipynb:4
