### ISSUE TITLE
Warning: tried to free model while optimization in progress

### ISSUE THREAD

**Issue by JackDunnNZ** [jump-dev/Gurobi.jl#377]
We are using Gurobi Compute Server along with lazy callbacks to solve many problems in sequence. There is some overhead when establishing the connection to the compute server, so we reuse an `Env` across the multiple solves, which successfully reuses the connection as hoped.

However, we sporadically see the following "warning", which actually causes the entire solve to hang indefinitely:

```
Warning: tried to free model while optimization in progress
```

As the message indicates, this happens when `GRBfreemodel` is called while a problem is being solved. 

I have traced this back and found that it is happening when the [finalizer](https://github.com/jump-dev/Gurobi.jl/blob/35ec720f086811e9e82c6607d2dff7b9503d3c1c/src/MOI_wrapper.jl#L245) of a model from an earlier problem is being fired during the solve of a subsequent problem. I'm guessing the GC is able to run right before the callback function enters, and when this happens it interrupts the solve and causes this issue. It seems weird to me that it would cause a problem, because I presume that each problem has a pointer to its own model (so maybe there is just a blanket restriction on calling `GRBfreemodel` on any model while any solve is running)?

I confirmed that if I manually run the GC between each solve then this resolves the problem, as any dangling models are freed before the next solve begins. This is a little heavy-handed though.

I thought about manually calling `finalize` on the model after each solve is finished, but I will admit I got a bit confused when trying to figure out how this interacts with the various possible backend types.

Do you think this is the right way to go about solving the issue, or have any other ideas? If so, I would welcome any pointers as to how to best try to run the finalizers manually.

Alternatively if I am thinking about this the wrong way entirely please feel free to point and laugh!

**Comment by odow** [comment]
> maybe there is just a blanket restriction on calling GRBfreemodel on any model while any solve is running

You should confirm this with Gurobi support, but that seems likely.

> if I manually run the GC between each solve then this resolves the problem

This seems reasonable. Alternatively, if you're not generating a lot of garbage during the lazy callbacks, you could use
```Julia
function safe_optimize!(model)
    GC.enable(false)
    optimize!(model)
    GC.enable(true)
    return
end
```

I can't think of a good way of fixing this on our side, so hacky work-arounds seem like the way to go. 

You should contact Gurobi support and request `GRBfreemodel` postpones execution if another solve is in progress, rather than throwing an error. I wonder how they manage this in their Python interface, since it probably has a similar issue.

**Comment by JackDunnNZ** [comment]
Thanks for confirming, hacks it is for now. Although your hack is a lot cleverer than mine, not sure how that slipped my mind.

I will relay to Gurobi support and see what they say

Thanks as always @odow

**Comment by odow** [comment]
What was the code for the compute server environment? Did it automatically pick it up from your license file? Or did you do something else?

**Comment by JackDunnNZ** [comment]
Yeah, it's super simple, you just have a license file like this and everything works automagically:

```
COMPUTESERVER=hostname:port
PASSWORD=secret
```

**Comment by JackDunnNZ** [comment]
FYI, Gurobi responded that this is expected behavior as a Gurobi environment is explicitly not thread-safe, and suggested either manually freeing the model between solves, or making sure the GC doesn't run during a solve.
