### ISSUE TITLE
Writing model to file

### ISSUE THREAD

**Issue by fa-bien** [jump-dev/Gurobi.jl#379]
I just found out that there have been breaking changes, as described at https://discourse.julialang.org/t/ann-upcoming-breaking-changes-to-cplex-jl-and-gurobi-jl/47814/7

I am now upgrading "old" code to the new version but I cannot find how to write a model to a file. I used to do the following: `write_model(backend(model).inner, filename)`

Now my understanding is that I need to write something like
        `GRBwrite(model, filename)`

However if I do that I get an error message:

`ERROR: MethodError: no method matching write_to_file(::JuMP.Model, ::String)
Closest candidates are:
  write_to_file(::Union{MathOptInterface.Utilities.UniversalFallback{MathOptInterface.FileFormats.MOF.InnerModel{Float64}}, MathOptInterface.FileFormats.CBF.Model, MathOptInterface.FileFormats.LP.Model, MathOptInterface.FileFormats.MPS.Model, MathOptInterface.FileFormats.SDPA.Model}, ::String) at /home/fabien/.julia/packages/MathOptInterface/ZJFKw/src/FileFormats/FileFormats.jl:99
`

**Comment by fa-bien** [comment]
Never mind, solved it by (i) using `direct_model()` and (ii) using `GRBwrite(backend(model), filename)`

**Comment by odow** [comment]
You should also be able to use `JuMP.write_to_file`:
```julia
using JuMP, Gurobi
model = Model(Gurobi.Optimizer)
# stuff...
write_to_file(model, "my_model.mps")
```
