### ISSUE TITLE
How can I terminate model in the callback function?

### ISSUE THREAD

**Issue by Wenbo11** [jump-dev/Gurobi.jl#381]
Hey,

I want to create multiple-terminating criteria in Gurobi like this example {https://support.gurobi.com/hc/en-us/articles/360047717291} in gurobipy.
I tried using ``GRBterminate(model)`` in callback function but an error raised 
``MethodError: no method matching unsafe_convert(::Type{Ptr{Nothing}}, ::UnitCommitmentModel)
Closest candidates are:
  unsafe_convert(::Type{Ptr{Nothing}}, !Matched::Base.RefValue{T}) where T at refvalue.jl:30
  unsafe_convert(::Type{Ptr{Nothing}}, !Matched::Base.RefArray{T,A,R} where R where A<:(AbstractArray{T,N} where N)) where T at refpointer.jl:90
  unsafe_convert(::Type{Ptr{Nothing}}, !Matched::Base.CFunction) at c.jl:36
  ...``
How can I terminate model in the callback function?

Thanks!

**Comment by odow** [comment]
Please follow the example: https://github.com/jump-dev/Gurobi.jl#callbacks

Here's an example calling `GRBterminate`:
https://github.com/jump-dev/Gurobi.jl/blob/35ec720f086811e9e82c6607d2dff7b9503d3c1c/test/MOI/MOI_wrapper.jl#L1019-L1028

Note that if you are using JuMP, you need to use `direct_model`. I don't know what `::UnitCommitmentModel` is, so it appears you are trying to use something other than a direct model via JuMP, or a `Gurobi.Optimizer`.

**Comment by Wenbo11** [comment]
Thanks for your replying, I attach my toy example:

```
function stop_criteria(cb_data, cb_where::Cint)
    if cb_where == GRB_CB_MIP
        
        primal_bound = Ref{Cdouble}() # a pointer
        GRBcbget(cb_data, cb_where, GRB_CB_MIP_OBJBST, primal_bound)
        
        dual_bound = Ref{Cdouble}()
        GRBcbget(cb_data, cb_where, GRB_CB_MIP_OBJBND, dual_bound)
        
        gap = abs((primal_bound[] - dual_bound[]) / primal_bound[])
        
        if gap < 0.03
            println("Terminate the solving ...")
            MOI.set(jump_model, Gurobi.CallbackFunction(), (cb_data, cb_where) -> begin
                GRBterminate(jump_model)
            end)
#             GRBterminate(jump_model)
        end
    end
end
MOI.set(jump_model, Gurobi.CallbackFunction(), stop_criteria)
JuMP.optimize!(jump_model)
```
Then  I got the error:
```
MethodError: no method matching unsafe_convert(::Type{Ptr{Nothing}}, ::Model)
Closest candidates are:
  unsafe_convert(::Type{Ptr{Nothing}}, !Matched::Base.RefValue{T}) where T at refvalue.jl:30
  unsafe_convert(::Type{Ptr{Nothing}}, !Matched::Base.RefArray{T,A,R} where R where A<:(AbstractArray{T,N} where N)) where T at refpointer.jl:90
  unsafe_convert(::Type{Ptr{Nothing}}, !Matched::Base.CFunction) at c.jl:36
  ...
```
Looks that the error will raise even I use 
```
     MOI.set(model, Gurobi.CallbackFunction(), (cb_data, cb_where) -> begin 
         GRBterminate(model) 
     end) 
```
in the example.

Any idea to solve it?
Many thanks!

**Comment by odow** [comment]
See https://github.com/jump-dev/Gurobi.jl/pull/382
