### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by hemoring** [jump-dev/Gurobi.jl#387]
I have tried installing Gurobi to use with Julia on ATOM/Juno several times and I cannot get it to work. I get this error message and it tells me to post it here so hopefully someone can help. I'm very new to this, the only coding experience I have really is with Matlab.
```
 Error: Error building `Gurobi`: 
│ ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
│ open an issue at https://github.com/jump-dev/Gurobi.jl and post the full
│ print-out of this diagnostic attempt.
│ 
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\hanna\.julia\packages\Gurobi\NE6Ff\deps\build.jl:161
│  [3] include(::String) at .\client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at C:\Users\hanna\.julia\packages\Gurobi\NE6Ff\deps\build.jl:155
│ 
│ **Unable to locate Gurobi installation. Running some common diagnostics.**
│ 
│ Gurobi.jl only supports the following versions:
│ 
│  - gurobi90
│  - gurobi91
│ 
│ Did you download and install one of these versions from gurobi.com?
│ Installing Gurobi.jl via the Julia package manager is _not_ sufficient!
│ 
│ Found GUROBI_HOME =  C:\Program Files\gurobi911\win64
│ 
│ Does this point to the correct install location?
│ 
│ We're going to look for the Gurobi library in this directory:
│     C:\Program Files\gurobi911\win64\bin
│ 
│ That directory has the following files:
│ 
│  - C:\Program Files\gurobi911\win64\bin\Gurobi91.NET.XML
│  - C:\Program Files\gurobi911\win64\bin\Gurobi91.NET.dll
│  - C:\Program Files\gurobi911\win64\bin\GurobiJni91.dll
│  - C:\Program Files\gurobi911\win64\bin\grb_ts.exe
│  - C:\Program Files\gurobi911\win64\bin\grbcluster.exe
│  - C:\Program Files\gurobi911\win64\bin\grbgetkey.exe
│  - C:\Program Files\gurobi911\win64\bin\grbprobe.exe
│  - C:\Program Files\gurobi911\win64\bin\grbtune.exe
│  - C:\Program Files\gurobi911\win64\bin\gurobi.bat
│  - C:\Program Files\gurobi911\win64\bin\gurobi91.dll
│  - C:\Program Files\gurobi911\win64\bin\gurobi91_light.dll
│  - C:\Program Files\gurobi911\win64\bin\gurobi_cl.exe
│  - C:\Program Files\gurobi911\win64\bin\vslauncher.exe
│  - C:\Program Files\gurobi911\win64\bin\vswhere.exe
│ 
│ We were looking for (but could not find) a file named like
│ `libgurobiXXX.so`, `libgurobiXXX.dylib`, or `gurobiXXX.dll`.
│ 
│ 
│ You should set the `GUROBI_HOME` environment variable to point to the
│ install location then try again. For example (updating the path to the
│ correct location if needed):
│ ```
│ # On Windows, this might be
│ ENV["GUROBI_HOME"] = "C:\\Program Files\\gurobi910\\win64\\"
│ import Pkg
│ Pkg.add("Gurobi")
│ Pkg.build("Gurobi")
│ 
│ # On OSX, this might be
│ ENV["GUROBI_HOME"] = "/Library/gurobi910/mac64/"
│ import Pkg
│ Pkg.add("Gurobi")
│ Pkg.build("Gurobi")
│ 
│ # On Unix, this might be
│ ENV["GUROBI_HOME"] = "/opt/gurobi910/linux64/"
│ import Pkg
│ Pkg.add("Gurobi")
│ Pkg.build("Gurobi")
│ ```
│ **Note: your path may differ. Check which folder you installed the Gurobi
│ binary in, and update the path accordingly.**
```

**Comment by odow** [comment]
That's weird. It certainly looks like it should have worked. What's the output of 
```Julia
using Libdl
Libdl.dlopen("C:\\Program Files\\gurobi911\\win64\\bin\\gurobi91.dll")
```

**Comment by hemoring** [comment]
julia> Libdl.dlopen("C:\\Program Files\\gurobi911\\win64\\bin\\gurobi91.dll")
ERROR: could not load library "C:\Program Files\gurobi911\win64\bin\gurobi91.dll"
%1 is not a valid Win32 application. 
Stacktrace:
 [1] dlopen(::String, ::UInt32; throw_error::Bool) at C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.5\Libdl\src\Libdl.jl:109
 [2] dlopen at C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.5\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
 [3] top-level scope at none:1

**Comment by odow** [comment]
It looks like you have 32-bit Julia installed. You need to install the 64-bit version: https://julialang.org/downloads/

**Comment by hemoring** [comment]
> That's weird. It certainly looks like it should have worked. What's the output of
> 
> ```julia
> using Libdl
> Libdl.dlopen("C:\\Program Files\\gurobi911\\win64\\bin\\gurobi91.dll")
> ```

julia> Libdl.dlopen("C:\Program Files\gurobi911\win64\bin\gurobi91.dll")
ERROR: could not load library "C:\Program Files\gurobi911\win64\bin\gurobi91.dll"
%1 is not a valid Win32 application.
Stacktrace:
[1] dlopen(::String, ::UInt32; throw_error::Bool) at C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.5\Libdl\src\Libdl.jl:109
[2] dlopen at C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.5\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
[3] top-level scope at none:1

**Comment by hemoring** [comment]
> It looks like you have 32-bit Julia installed. You need to install the 64-bit version: https://julialang.org/downloads/



> It looks like you have 32-bit Julia installed. You need to install the 64-bit version: https://julialang.org/downloads/

thank you!

**Comment by odow** [comment]
> thank you!

No problem.
