### ISSUE TITLE
Installing Issues

### ISSUE THREAD

**Issue by GuilleHele** [jump-dev/Gurobi.jl#391]
Dear community:

I´m looking to install Gurobi in order to use it for the SDDP library, I follow the instruction in gurobi.com, got my license and I activated in the Gurobi command. But when I follow the installment instructions it says that Gurobi.jl does not support the latest version 9.1.1, maybe I did something wrong, I would like to get your help. I´m using windows.

This is the code that I used:
`ENV["GUROBI_HOME"] = "C:\\gurobi911\\win64"`
`Pkg.add("Gurobi")`
`Pkg.build("Gurobi")`

And I get the following message:

> ┌ Error: Error building `Gurobi`: 
│ ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
│ open an issue at https://github.com/JuliaOpt/Gurobi.jl and post the full
│ print-out of this diagnostic attempt.
│ 
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\Guillermo\.julia\packages\Gurobi\VhpiN\deps\build.jl:154
│  [3] include(::String) at .\client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at C:\Users\Guillermo\.julia\packages\Gurobi\VhpiN\deps\build.jl:152
│ Unable to locate Gurobi installation. Running some common diagnostics.
│ 
│ Gurobi.jl only supports the following versions:
│ 
│  - gurobi90
│  - gurobi81
│  - gurobi80
│  - gurobi75
│  - gurobi70
│ 
│ Did you download and install one of these versions from gurobi.com?
│ 
│ 
│ Found GUROBI_HOME =  C:\gurobi911\win64
│ 
│ Does this point to the correct install location?
│ - on Windows, this might be `C:\Program Files\gurobi810\win64\`
│ - alternatively, on Windows, this might be `C:/Program Files/gurobi810/win64/`
│ - on OSX, this might be `/Library/gurobi810/mac64/`
│ - on Unix, this might be `/home/my_user/gurobi810/linux64/`
│ 
│ Note: this has to be a full path, not a path relative to your current
│ directory or your home directory.
│ 
│ We're going to look for the Gurobi library in this directory:
│     C:\gurobi911\win64\bin
│ 
│ That directory has the following files:
│ 
│  - C:\gurobi911\win64\bin\Gurobi91.NET.XML
│  - C:\gurobi911\win64\bin\Gurobi91.NET.dll
│  - C:\gurobi911\win64\bin\GurobiJni91.dll
│  - C:\gurobi911\win64\bin\grb_ts.exe
│  - C:\gurobi911\win64\bin\grbcluster.exe
│  - C:\gurobi911\win64\bin\grbgetkey.exe
│  - C:\gurobi911\win64\bin\grbprobe.exe
│  - C:\gurobi911\win64\bin\grbtune.exe
│  - C:\gurobi911\win64\bin\gurobi.bat
│  - C:\gurobi911\win64\bin\gurobi91.dll
│  - C:\gurobi911\win64\bin\gurobi91_light.dll
│  - C:\gurobi911\win64\bin\gurobi_cl.exe
│  - C:\gurobi911\win64\bin\vslauncher.exe
│  - C:\gurobi911\win64\bin\vswhere.exe
│ 
│ We were looking for (but could not find) a file named like
│ `libgurobiXXX.so`, `libgurobiXXX.dylib`, or `gurobiXXX.dll`. You
│ should update your GUROBI_HOME environment variable to point to the
│ correct location. 

Also in a similar issue I run the following code:
`using Libdl`
`Libdl.dlopen("C:\\gurobi911\\win64\\bin\\gurobi91.dll")`

And it runs without problems, meaning that I downloaded the correct Atom.

I thank you in advance for your help, if I can provide any more information let me know.

Sincerely,

**Comment by odow** [comment]
I looks like you've installed an old version of Gurobi.jl somehow. What's the output of 
```Julia
] add Gurobi@0.9.7
```

**Comment by GuilleHele** [comment]
I don´t know did I manage to install an old version of the library haha, but your line of code, worked wonderfully, thank you so much for your help!

**Comment by odow** [comment]
No problem.
