### ISSUE TITLE
MIP problems only use a single core during branch-and-bound

### ISSUE THREAD

**Issue by niclasmattsson** [jump-dev/Gurobi.jl#402]
I posted this on Gurobi's support forum too. It's still pending approval by the mods there but I'm opening this issue immediately here because I very much doubt Gurobi would miss a problem like this in the general release. (On the other hand, I also kind of doubt the problem is in Gurobi.jl since all cores are being used in the LP root relaxation.)

> I just upgraded from Gurobi 9.0.3 to 9.1.1 and noticed that MIPs were solving much slower than in the previous release. After inspecting CPU usage in Windows task manager during the solve I noticed that Gurobi was only using a single core during the MIP phase in 9.1.1. All cores are used in Barrier in LP problems or during the root relaxation phase of MIPs, but only a single core during branch-and-bound. I have the Threads parameter set to 12. When I downgrade to 9.0.3 again everything is fine - i.e. all cores are used during the MIP phase using the exact same code.
>
> I get the same behavior on two different machines. Is this just me, a problem with Julia's Gurobi interface or a general Gurobi issue?

Can anyone else confirm or contradict this problem? Unfortunately I can't share the model this happens on, but if needed I'll create another MIP for public consumption.

**Comment by odow** [comment]
This seems like a Gurobi issue, not a Gurobi.jl issue (Gurobi.jl is not officially supported by Gurobi).

They probably changed a heuristic that decides how many threads to use (it may decide to use a single thread if it estimates that the cost of solving the problem on a single thread is less than the overhead of starting new threads and copying the data-structures).

**Comment by niclasmattsson** [comment]
Thanks, that sounds reasonable. But if your guess is correct then their heuristic isn't working well for my problem at least, and I wish I could override it with a parameter setting. I'll update this thread next week with their official response in case someone else has the same problem.

**Comment by odow** [comment]
You could try tuning the problem: https://github.com/jump-dev/Gurobi.jl/blob/e4c2a41d2f8926558318b3f7852df41d2676200b/src/gen91/libgrb_api.jl#L829-L835 Their online C documentation explains how to use each function. 

You need something like
```Julia
model = direct_model(Gurobi.Optimizer())
ret = GRBtunemodel(backend(model))
```

**Comment by niclasmattsson** [comment]
Thanks for the tip, I didn't know that you could tune models from within Julia. I got a response from Gurobi support so I'll post it here in case someone else finds this behavior strange:

> The drop which you see in the core usage is actually an improvement. What you see with version 9.1.1 is that the parallel threads have finished their work at the root node and are released to make them usable by the overall system. Once the main thread finishes its work in the root node, the additional threads are re-used again in the actual B&B procedure, i.e., when the number of nodes in the tree gets larger than 0. What you see in version 9.0.3 is that although these threads have finished their work in the root node and are waiting for the main thread, they are not freed and are thus kept occupied for no real reason.

So it seems they're saying that this is a bugfix, that Gurobi 9.0.3 was using 100% on all cores even though it was basically idling. I've now confirmed that multiple cores are indeed being used later during branch-and-bound, but in my current model that doesn't happen until 3.5 hours of root node heuristics (using just a single core) have finished. So I asked about that too:

> Root node heuristics use multiple threads. However, in this particular instance all helper threads finish quickly and are released while the main thread keeps working/sitting in an expensive heuristic/loop.

It's a bit strange that I can't detect any use of multiple CPU cores at the root node, but I guess I'll have to take their word for it. Just thought I'd share. Closing since this has nothing to do with Gurobi.jl.

**Comment by odow** [comment]
You're probably better to disable things like this: https://www.gurobi.com/documentation/9.1/refman/minrelnodes.html, and/or provide an initial feasible solution as a starting point.
