### ISSUE TITLE
How to use OR(disjunction) constraint in gurobi ?

### ISSUE THREAD

**Issue by LLwyct** [jump-dev/Gurobi.jl#404]
I have 10 variables(v0, v1, v2, ..., v9), and be outputed from handwritten digit recognition. They are in range [0, 1].

now i need a Vmodel, and variables satisify the following constraints:
```
v0 >= v7 || v1>=v7 || v2>=v7 || v3>=v7 || v4>=v7 || v5>=v7 || v6>=v7 || v8>=v7 || v9>=v7
```
how can i use model.addConstr() to add this OR constraint ?

**Comment by odow** [comment]
1. Use the C API https://github.com/jump-dev/Gurobi.jl/blob/d9cebe4ec05a102df8917ff2602e6c38abdac090/src/gen91/libgrb_api.jl#L209-L211

2. Reformulate as a MIP:
```julia

**Comment by LLwyct** [comment]
@odow 
thank you, I sloved this problem by a simple way.

first, create additional 9 binary Vars[9].

then use `GenConstrIndicator`
```py
for i in range:
    model.addConstr((Vars[i] == 1) >> v[i] >= v[7])
```

then add constr
```py
model.addConstr(quicksum(Vars) >= 1)
model.addConstr(quicksum(Vars) <= 9)
```
