### ISSUE TITLE
How to use feasRelax in Gurobi ? 

### ISSUE THREAD

**Issue by duc082014** [jump-dev/Gurobi.jl#407]
I have some constraints that should be allowed to be violated for creating a feasibility relaxation. How can i use C API GRBModel::feasRelax() to do that?

**Comment by odow** [comment]
Use the C API: https://www.gurobi.com/documentation/9.1/refman/c_feasrelax.html

```Julia
using JuMP, Gurobi
jump_model = direct_model(Gurobi.Optimizer())
model = backend(jump_model)
```
Then pass `model` to `GRBfeasrelax`:
https://github.com/jump-dev/Gurobi.jl/blob/d9cebe4ec05a102df8917ff2602e6c38abdac090/src/gen91/libgrb_api.jl#L301-L303

You should be aware that this operation is advanced, and that Gurobi.jl is not officially supported by Gurobi.

**Comment by odow** [comment]
There is only one signature in the Gurobi documentation, which is identical to this one. 

```Julia
using JuMP, Gurobi
jump_model = direct_model(Gurobi.Optimizer())
model = backend(jump_model)
penalties = Cdouble[] 
error = GRBfeasrelax(model, 0, 0, C_NULL, C_NULL, penalties, C_NULL)
```
