### ISSUE TITLE
Tune model

### ISSUE THREAD

**Issue by anavarro01** [jump-dev/Gurobi.jl#421]
Hi, i am trying to tune my Gurobi model, calling de tune function (https://www.gurobi.com/documentation/9.1/refman/py_model_tune.html). I followed the instructions from #138 , but it seems to not work at the 9.1 version. There is any waiy to use this utility?

**Comment by odow** [comment]
Use the C API:
https://github.com/jump-dev/Gurobi.jl/blob/6484ba968b09526f13bb8cb5a1fe27abc82bb627/src/gen91/libgrb_api.jl#L833-L835

```Julia
using JuMP, Gurobi
jump_model = direct_model(Gurobi.Optimizer())
model = backend(jump_model)
GRBtunemodel(model)
```

You should consult the Gurobi documentation for more details.

**Comment by odow** [comment]
Closing because this isn't an issue in Gurobi.jl. 

Issue #412 is tracking the addition of documentation for accessing the C API.
