### ISSUE TITLE
An error occurs when I am enquiring the optimal values after having deleted a constraint 

### ISSUE THREAD

**Issue by xgandibleux** [jump-dev/Gurobi.jl#423]
Hi,
I noticed a difference between GLPK and GUROBI when a constraint is deleted.
With GLPK, after having deleted a constraint, the optimal solution remains available.
With GUROBI, an error occurs. I suppose that the problem is located on the interface with gurobi at MOI level.

My config is the following:
*  Julia : 1.6.2
*  GLPK v0.14.12
*  Gurobi v0.9.14
*  JuMP v0.21.10
*  macOS bigsur

Here after the code used, and the outputs:

```julia
using JuMP

using GLPK
mymodel = Model(GLPK.Optimizer)
#using Gurobi
#mymodel = Model(Gurobi.Optimizer)

@variable(mymodel, 0<= x[i=1:2])
@objective(mymodel, Min, 2x[1] + 3x[2])
@constraint(mymodel, c1, x[2] >= 3)
@constraint(mymodel, c2, x[1] >= 7)
print(mymodel)
optimize!(mymodel)
println("before :",termination_status(mymodel))
println("before :",JuMP.value.(x))
delete(mymodel,c1)
delete(mymodel,c2)
print(mymodel)
println("after : ",termination_status(mymodel))
println("after : ",JuMP.value.(x))
```

GLPK: ——————————————————————————————

julia> using JuMP

julia> using GLPK

julia> mymodel = Model(GLPK.Optimizer)
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: GLPK

julia> @variable(mymodel, 0<= x[i=1:2])
2-element Vector{VariableRef}:
 x[1]
 x[2]

julia> @objective(mymodel, Min, 2x[1] + 3x[2])
2 x[1] + 3 x[2]

julia> @constraint(mymodel, c1, x[2] >= 3)
c1 : x[2] ≥ 3.0

julia> @constraint(mymodel, c2, x[1] >= 7)
c2 : x[1] ≥ 7.0

julia> print(mymodel)
Min 2 x[1] + 3 x[2]
Subject to
 c1 : x[2] ≥ 3.0
 c2 : x[1] ≥ 7.0
 x[1] ≥ 0.0
 x[2] ≥ 0.0

julia> optimize!(mymodel)

julia> println("before :",termination_status(mymodel))
before :OPTIMAL

julia> println("before :",JuMP.value.(x))
before :[7.0, 3.0]

julia> delete(mymodel,c1)

julia> delete(mymodel,c2)

julia> print(mymodel)
Min 2 x[1] + 3 x[2]
Subject to
 x[1] ≥ 0.0
 x[2] ≥ 0.0

julia> println("after : ",termination_status(mymodel))
after : OPTIMAL

julia> println("after : ",JuMP.value.(x))
after : [7.0, 3.0]

GUROBI: ——————————————————————————————

julia> using JuMP

julia> using Gurobi

julia> mymodel = Model(Gurobi.Optimizer)
Academic license - for non-commercial use only - expires 2021-11-05
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: Gurobi

julia> @variable(mymodel, 0<= x[i=1:2])
2-element Vector{VariableRef}:
 x[1]
 x[2]

julia> @objective(mymodel, Min, 2x[1] + 3x[2])
2 x[1] + 3 x[2]

julia> @constraint(mymodel, c1, x[2] >= 3)
c1 : x[2] ≥ 3.0

julia> @constraint(mymodel, c2, x[1] >= 7)
c2 : x[1] ≥ 7.0

julia> print(mymodel)
Min 2 x[1] + 3 x[2]
Subject to
 c1 : x[2] ≥ 3.0
 c2 : x[1] ≥ 7.0
 x[1] ≥ 0.0
 x[2] ≥ 0.0

julia> optimize!(mymodel)
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (mac64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 2 rows, 2 columns and 2 nonzeros
Model fingerprint: 0xb40b3832
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e+00, 3e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [3e+00, 7e+00]
Presolve removed 2 rows and 2 columns
Presolve time: 0.00s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    2.3000000e+01   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.00 seconds
Optimal objective  2.300000000e+01

User-callback calls 24, time in user-callback 0.00 sec

julia> println("before :",termination_status(mymodel))
before :OPTIMAL

julia> println("before :",JuMP.value.(x))
before :[7.0, 3.0]

julia> delete(mymodel,c1)

julia> delete(mymodel,c2)

julia> print(mymodel)
Min 2 x[1] + 3 x[2]
Subject to
 x[1] ≥ 0.0
 x[2] ≥ 0.0

julia> println("after : ",termination_status(mymodel))
after : OPTIMIZE_NOT_CALLED

julia> println("after : ",JuMP.value.(x))
ERROR: OptimizeNotCalled()
Stacktrace:
  [1] _moi_get_result(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ModelFunctionConstraints{Float64}}}}, ::MathOptInterface.VariablePrimal, ::Vararg{Any, N} where N)
    @ JuMP ~/.julia/packages/JuMP/e0Uc2/src/JuMP.jl:846
  [2] get(model::Model, attr::MathOptInterface.VariablePrimal, v::VariableRef)
    @ JuMP ~/.julia/packages/JuMP/e0Uc2/src/JuMP.jl:878
  [3] value(v::VariableRef; result::Int64)
    @ JuMP ~/.julia/packages/JuMP/e0Uc2/src/variables.jl:767
  [4] value
    @ ~/.julia/packages/JuMP/e0Uc2/src/variables.jl:767 [inlined]
  [5] _broadcast_getindex_evalf
    @ ./broadcast.jl:648 [inlined]
  [6] _broadcast_getindex
    @ ./broadcast.jl:621 [inlined]
  [7] getindex
    @ ./broadcast.jl:575 [inlined]
  [8] macro expansion
    @ ./broadcast.jl:984 [inlined]
  [9] macro expansion
    @ ./simdloop.jl:77 [inlined]
 [10] copyto!
    @ ./broadcast.jl:983 [inlined]
 [11] copyto!
    @ ./broadcast.jl:936 [inlined]
 [12] copy
    @ ./broadcast.jl:908 [inlined]
 [13] materialize(bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(value), Tuple{Vector{VariableRef}}})
    @ Base.Broadcast ./broadcast.jl:883
 [14] top-level scope
    @ REPL[16]:1

julia>

**Comment by odow** [comment]
This is warned against in the JuMP documentation: https://jump.dev/JuMP.jl/stable/manual/solutions/#Recommended-workflow

Modifying a model may invalidate the solution. You should query before modification.

**Comment by odow** [comment]
Closing in favor of https://github.com/jump-dev/JuMP.jl/pull/2709
