### ISSUE TITLE
Attributes should define is_set_by_optimize

### ISSUE THREAD

**Issue by odow** [jump-dev/Gurobi.jl#425]
See the discussions here:
https://github.com/jump-dev/JuMP.jl/issues/2587
https://github.com/jump-dev/JuMP.jl/pull/2784

**Comment by metab0t** [comment]
Does https://github.com/jump-dev/JuMP.jl/issues/2587#issuecomment-834065020 solve the problem?
Based on fix of JuMP side above, should we define the following code here to solve this problem?
```julia
MOI.is_set_by_optimize(::ModelAttribute) = true
MOI.is_set_by_optimize(::VariableAttribute) = true
MOI.is_set_by_optimize(::ConstraintAttribute) = true
```

**Comment by odow** [comment]
Yes, I think that's sufficient for now.
