### ISSUE TITLE
MOI lazy constraints callback not called at MIPNODE

### ISSUE THREAD

**Issue by simonbowly** [jump-dev/Gurobi.jl#426]
From the [JuMP solver independent callbacks examples](https://jump.dev/JuMP.jl/stable/manual/callbacks/#Things-you-can-and-cannot-do-during-solver-independent-callbacks) it should be possible for fractional solutions to reach a lazy constraints callback.

MOI_callbacks.jl only calls the lazy constraints callback (if it exists) when where=MIPSOL, so fractional node solutions can never reach the callback. This is contrary to the behaviour of the example code when using GLPK.

https://github.com/jump-dev/Gurobi.jl/blob/374a569f71dffa178092d73fda58f93a537ae425/src/MOI_wrapper/MOI_callbacks.jl#L126-L152

```
function my_callback_function(cb_data)
    status = callback_node_status(cb_data, model)
    if status == MOI.CALLBACK_NODE_STATUS_FRACTIONAL
        # `callback_value(cb_data, x)` is not integer (to some tolerance).
        # <-- NOT reachable with Gurobi.jl backend -->
    elseif status == MOI.CALLBACK_NODE_STATUS_INTEGER
        # `callback_value(cb_data, x)` is integer (to some tolerance).
    else
        @assert status == MOI.CALLBACK_NODE_STATUS_UNKNOWN
        # `callback_value(cb_data, x)` might be fractional or integer.
    end
    ...
end
MOI.set(model, MOI.LazyConstraintCallback(), my_callback_function)
```

**Comment by odow** [comment]
This is actually super tricky to get right:

![image](https://user-images.githubusercontent.com/8177701/139755244-cad17489-4592-403d-9cc7-0af7a93c49b6.png)

I can't find the original discussion, but I believe we had issues on fractional nodes. But now we have `CallbackNodeStatus` that isn't an issue.

**Comment by blegat** [comment]
Related discussion: https://github.com/jump-dev/GLPK.jl/issues/146

**Comment by pszufe** [comment]
Hi,
This change turned out to be breaking for my code. Is there any parameter to restore previous behavior?

I am running a complex extension of a TSP model and make callbacks to avoid cycles (a classic callback application). 
Up to `Gurobi#v0.10.0` I would be getting callbacks only at a feasible solution. 
Now I am trying to rerun  my code from October 2021 using `Gurobi#v0.10.1` (or later) and now I am getting callbacks at infeasible solutions - and of course there is no good way to process them to yield new constraints for my model.

What should I do to make sure that I am getting callbacks only at feasible solutions? I guess this could be a very important information for other users of `Gurobi.jl`.

**Comment by odow** [comment]
Check `callback_node_status(cb_data, model)` to see if the node is integer or fractional.

Here's a general example:

https://jump.dev/JuMP.jl/stable/manual/callbacks/#Lazy-constraints

and a TSP-specific example:

https://jump.dev/JuMP.jl/stable/tutorials/algorithms/tsp_lazy_constraints/#Lazy-constraint-method

**Comment by WalterMadelim** [comment]
@odow There is a bit issue about the language.
> The lazy constraint callback may be called at fractional or integer nodes in the branch-and-bound tree. There is no guarantee that the callback is called at every primal solution.

A node in the branch-and-cut tree is an LP. 
We don't say "the node is integer" or "the node is fractional".
If the relaxed solution for `x` is fractional, but `x` in the `model` has integer constraint on it, then the solver might deliver a fractional solution within the callback function when `cb_where == MIPNODE`.

**Comment by odow** [comment]
Hi @WalterMadelim, please don't comment on long closed issues. If you have suggestions for improvements to the documentation, please make a pull request.
