### ISSUE TITLE
Force recompilation when deps.jl changes

### ISSUE THREAD

**Issue by ExpandingMan** [jump-dev/Gurobi.jl#438]
It's really nice that this is now downloading an artifact, however it's really screwing up a case in which I have an older computer server running which is incompatible with 0.9.5.

I was hoping that by setting `GUROBI_HOME` when Gurobi.jl gets built it would use that and not try to use the artifact, however I couldn't seem to get it to do this.

I suggest
- If no `GUROBI_HOME` is set, use artifacts as it currently does.
- If `GUROBI_HOME` is set, skip artifacts and just use that.

**Comment by ExpandingMan** [comment]
Looks like what I described above was intended... seems to be a very strange bug... `_DEPS_FILE` exists but it is using the artifact version of `ligburobi`... very weird...

**Comment by ExpandingMan** [comment]
Figured it out... apparently Julia bakes the value of `libgurobi` into the pre-compile cache.  For this package, this should probably be circumvented so that one can change the binary location just by doing `Pkg.build("Gurobi")`, though I'm not sure what is the most appropriate way of doing that.

**Comment by odow** [comment]
We use existing binaries if a `deps.jl` file is present:
https://github.com/jump-dev/Gurobi.jl/blob/1008e8cf2e11ec0e8ed846f55757ffe9aefd5c14/src/Gurobi.jl#L7-L8

> so that one can change the binary location just by doing Pkg.build("Gurobi")

Does this not work? If re-building a package doesn't force recompilation, that should be a Julia problem. I don't think we can fix that in Gurobi.jl.

I don't have a linux machine to test this further, unfortunately.

**Comment by ExpandingMan** [comment]
Like I said, I actually had to delete the pre-compile cache before it would use a new value for `libgurobi`.  This seems like it warrants a fix, but I'm not sure what the best way of fixing it is.  A solution which would certainly work but is rather hackish and seems liable to have undesirable side effects would be to just delete the pre-compile cache (I'm not sure off the top of my head if there is a Pkg API call for this).

I will ask around on zulip and slack, I'm sure someone will know what the "right" way of doing this is.

**Comment by odow** [comment]
> If re-building a package doesn't force recompilation, that should be a Julia problem

I'd regard this as a bug in Julia. Is this something we can actually fix in Gurobi.jl?

**Comment by ExpandingMan** [comment]
It's a bit more subtle than that, the `*.ji` files don't actually store compiled code.  Furthermore I don't think `const` is intended to be used this way, it probably should be a `ref` that gets selected when the package initializes.

Regardless, I see a few options here:
- Do nothing, but document the issue so that users can delete the `*.ji` cache manually as needed.
- Delete all gurobi `*.ji` files in the build script.
- Use a `Ref` and check the presence of the library at package initialization.

I took a look [here](https://github.com/JuliaGPU/VulkanCore.jl/blob/master/src/LibVulkan.jl) for how other libraries deal with this, and, at least in the Vulkan example, it uses a `Ref`, though as that package is an automated wrapper it's a less than ideal comparison.  Other examples I thought of all use `jll` and work a bit differently.

**Comment by odow** [comment]
Do you have a link to the slack conversation?

**Comment by ExpandingMan** [comment]
We had [this conversation](https://julialang.zulipchat.com/#narrow/stream/225542-helpdesk/topic/clearing.20values.20in.20pre-compile.20cache.20on.20.60Pkg.2Ebuild.60) on zulip.  Most of what I said here was from my own investigation.  Someone more familiar with `Pkg` related stuff might still have something valuable to contribute here.

**Comment by odow** [comment]
We probably can make this work with an `__init__` function. PRs accepted, but I have no plans to work on this.

The slack conversation (for the next few days before it gets purged) is: https://julialang.slack.com/archives/CBF3Z1D7V/p1637523109151900

**Comment by odow** [comment]
@kristofferc 's suggestion from slack is to use https://docs.julialang.org/en/v1/base/base/#Base.include_dependency.
