### ISSUE TITLE
Massive performance regression with bilinear constraints since Gurobi.jl v0.10

### ISSUE THREAD

**Issue by niclasmattsson** [jump-dev/Gurobi.jl#446]
Ever since Gurobi.jl v0.10 my bilinear models "freeze up" completely after calling `optimize!` for up to a full hour before they begin to solve, with the dreaded "Warning: excessive time spent in model updates". I noted the passage in the README about `GRBupdatemodel` so I just assumed the problem was on my end. But today I finally had time to dig deeper and I now think this is a legitimate performance regression. Here's an MWE, first the setup:

```julia
using JuMP, Gurobi

function lpmodel(n)
    m = Model()
    @variable(m, x[1:n] >= 0)
    @variable(m, y[1:n] >= 0)
    @variable(m, z[1:n] >= 0)
    @constraint(m, con[i in 1:n], z[i] == x[i] + y[i])
    @objective(m, Min, sum(z))
    optimizer = optimizer_with_attributes(Gurobi.Optimizer, "nonconvex" => 2)
    set_optimizer(m, optimizer)
    return m
end

function bilinearmodel(n)
    m = Model()
    @variable(m, x[1:n] >= 0)
    @variable(m, y[1:n] >= 0)
    @variable(m, z[1:n] >= 0)
    @constraint(m, con[i in 1:n], z[i] == x[i] * y[i])
    @objective(m, Min, sum(z))
    optimizer = optimizer_with_attributes(Gurobi.Optimizer, "nonconvex" => 2)
    set_optimizer(m, optimizer)
    return m
end

dummy1 = lpmodel(2)
dummy2 = bilinearmodel(2)

lp = lpmodel(50000)
bilinear = bilinearmodel(50000)

optimize!(dummy1);
optimize!(dummy2);
```

And now the results with timings. First we have Gurobi v0.9.14 and JuMP v0.21.10 (quick result, no problem).

```julia
(GurobiTest) pkg> status
      Status `C:\Stuff\Julia\GurobiTest\Project.toml`
  [2e9cd046] Gurobi v0.9.14
  [4076af6c] JuMP v0.21.10

julia> @time optimize!(lp);
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 50000 rows, 150000 columns and 150000 nonzeros
Model fingerprint: 0x5e77a4c3
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [0e+00, 0e+00]

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Presolve removed 50000 rows and 150000 columns
Presolve time: 0.06s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved with dual simplex
Solved in 0 iterations and 0.09 seconds
Optimal objective  0.000000000e+00

User-callback calls 30, time in user-callback 0.00 sec
  0.322845 seconds (650.84 k allocations: 94.467 MiB, 6.39% gc time)

julia> @time optimize!(bilinear);
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 0 rows, 150000 columns and 0 nonzeros
Model fingerprint: 0x21f34d2f
Model has 50000 quadratic constraints
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  QMatrix range    [1e+00, 1e+00]
  QLMatrix range   [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [0e+00, 0e+00]

Continuous model is non-convex -- solving as a MIP.

Found heuristic solution: objective 0.0000000

Explored 0 nodes (0 simplex iterations) in 0.04 seconds
Thread count was 1 (of 12 available processors)

Solution count 1: 0

Optimal solution found (tolerance 1.00e-04)
Best objective 0.000000000000e+00, best bound 0.000000000000e+00, gap 0.0000%

User-callback calls 27, time in user-callback 0.00 sec
  0.275316 seconds (850.83 k allocations: 102.430 MiB, 17.09% gc time)
```

And now Gurobi v0.10.1 with JuMP v0.22.2 (slow bilinear result):

```julia
(GurobiTest) pkg> status
      Status `C:\Stuff\Julia\GurobiTest\Project.toml`
  [2e9cd046] Gurobi v0.10.1
  [4076af6c] JuMP v0.22.2

julia> @time optimize!(lp);
Set parameter NonConvex to value 2
Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 50000 rows, 150000 columns and 150000 nonzeros
Model fingerprint: 0x5e77a4c3
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [0e+00, 0e+00]

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Presolve removed 50000 rows and 150000 columns
Presolve time: 0.06s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved with dual simplex
Solved in 0 iterations and 0.10 seconds (0.05 work units)
Optimal objective  0.000000000e+00

User-callback calls 33, time in user-callback 0.00 sec
  0.514082 seconds (1.95 M allocations: 220.513 MiB, 8.41% gc time)

julia> @time optimize!(bilinear);
Set parameter NonConvex to value 2
Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Warning: excessive time spent in model updates.
Consider calling update less frequently.

Optimize a model with 0 rows, 150000 columns and 0 nonzeros
Model fingerprint: 0x21f34d2f
Model has 50000 quadratic constraints
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  QMatrix range    [1e+00, 1e+00]
  QLMatrix range   [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [0e+00, 0e+00]

Continuous model is non-convex -- solving as a MIP

Found heuristic solution: objective 0.0000000

Explored 0 nodes (0 simplex iterations) in 0.04 seconds (0.02 work units)
Thread count was 1 (of 12 available processors)

Solution count 1: 0

Optimal solution found (tolerance 1.00e-04)
Best objective 0.000000000000e+00, best bound 0.000000000000e+00, gap 0.0000%

User-callback calls 31, time in user-callback 0.00 sec
 48.613892 seconds (2.15 M allocations: 230.431 MiB, 0.12% gc time)
```

I get the same (slow) result when I try downgrading Gurobi.jl to v0.10.0, or JuMP to 0.22.0. And same thing with the latest package versions but downgrading the Gurobi solver from version 9.5 to 9.1.1.

The freeze occurs between lines `Set parameter NonConvex to value 2` and `Gurobi Optimizer version 9.5.0 build v9.5.0rc5 (win64)`, so I'm pretty sure this is during model generation and not solving.

**Comment by odow** [comment]
Nothing immediately springs to mind as the problem, so this is going to take some debugging. I don't think we've changed anything to do with the quadratic stuff in a while.

> And same thing with the latest package versions but downgrading the Gurobi solver from version 9.5 to 9.1.1.

What does this mean? The same version of Gurobi.jl, but different upstream versions of Gurobi? That might mean you should contact Gurobi support.

cc @simonbowly

**Comment by niclasmattsson** [comment]
> What does this mean? The same version of Gurobi.jl, but different upstream versions of Gurobi? That might mean you should contact Gurobi support.

Yes. You'll notice above that the upstream Gurobi solver version was 9.1.1 in the fast example with Gurobi.jl v0.9.14, and autoswitched to 9.5 in the slow example with Gurobi.jl v0.10.2. To me that suggested that the problem could be in the upsteam solver, so I also tested with solver 9.1.1 in Gurobi.jl v0.10.2 and got the same slow result. My conclusion from this was the problem was probably **not** upstream. BTW all this is in Julia 1.7.1 on Windows 10, forgot to mention that earlier.

**Comment by odow** [comment]
> I also tested with solver 9.1.1 in Gurobi.jl v0.10.2 and got the same slow result

Ah okay. I got a bit confused. 

I don't have any time to look into this in any detail, but here's the diff between Gurobi 0.9.14 and 0.10.0:
https://github.com/jump-dev/Gurobi.jl/compare/v0.9.14...v0.10.0

It'll probably take some debugging. A good start would be to try:
```julia
function bilinearmodel(n)
    m = direct_model(Gurobi.Optimizer())
    set_optimizer_attribute(m, "nonconvex", 2)
    @variable(m, x[1:n] >= 0)
    @variable(m, y[1:n] >= 0)
    @variable(m, z[1:n] >= 0)
    @constraint(m, con[i in 1:n], z[i] == x[i] * y[i])
    @objective(m, Min, sum(z))
    return m
end
```

**Comment by niclasmattsson** [comment]
Interesting idea and result. I'm not familiar with how `direct_model()` works, so maybe you expected this. I get a similar delay (about 50% longer even), but the freeze now happens during the call to `bilinearmodel` while `optimize!` is instantaneous.

**Comment by odow** [comment]
You'll have to do some profiling to figure out where the time is being spent: https://github.com/timholy/ProfileView.jl

What if you don't name `con`? So `@constraint(m, [i in 1:n], z[i] == x[i] * y[i])`?

**Comment by niclasmattsson** [comment]
Sorry for the delay in following up on this - work and life conspired to eat all my spare time. But I had some time today while waiting for other model runs. Good news: you were right, not naming the constraint avoids the problem. So that gives me an acceptable workaround until this gets fixed. I ran ProfileView for you, below is a link to a zip archive with saved profiles. The problem run is `bilinear_named.jlprof` and the same run with unnamed constraints is `bilinear_unnamed.jlprof`. (Load by running `ProfileView.view(nothing)` and clicking open.)
https://chalmersuniversity.box.com/s/sjflcskuokiwfie11sb636p23ktcqokx

**Comment by odow** [comment]
Okay. I know the problem. There's an extra `_update_if_necessary` in
https://github.com/jump-dev/Gurobi.jl/blob/14208cd5733305d784f6462a261feda6a4e59af8/src/MOI_wrapper/MOI_wrapper.jl#L2487-L2501

We should make it like the affine function
https://github.com/jump-dev/Gurobi.jl/blob/14208cd5733305d784f6462a261feda6a4e59af8/src/MOI_wrapper/MOI_wrapper.jl#L2214-L2229
