### ISSUE TITLE
Bug in Gurobi v0.11.0 solver settings

### ISSUE THREAD

**Issue by karimianfard** [jump-dev/Gurobi.jl#460]
Hello every one
I am using the latest version of Gurobi. I get an error when I try to configure the solver. (According to the attached photo). Note that Gurobi solver is installed correctly.
![image](https://user-images.githubusercontent.com/84530547/156787466-fab20cf9-584f-4238-b93c-f37ffef075b8.png)

Please let me know how to configure "NonConvex=2" in the latest version of Gurobi.
Thanks

**Comment by odow** [comment]
For posterity:
```Julia
using JuMP
using Gurobi
model = Model(Gurobi.Optimizer)
set_optimizer_attribute(model, "NonConvex", 2)
```
