### ISSUE TITLE
Setting TimeLimit globally in Gurobi.jl or JuMP.jl

### ISSUE THREAD

**Issue by delft52** [jump-dev/Gurobi.jl#471]
Is there a way to set the Gurobi TimeLimit globally in the code, i.e., not for a specific model? I'm solving a MIP in a loop, and each time, Gurobi 9.5.1 displays the message "Set parameter TimeLimit to value ...", which makes reading my code messages and monitoring the execution progress difficult.

**Comment by odow** [comment]
> Is there a way to set the Gurobi TimeLimit globally in the code

No. Although you might be able to re-use an `Env`. (I didn't test this)
```Julia
env = Gurobi.Env()
GRBsetdblparam(env, "TimelImit", 1.0)

for _ in 1:3
    model = Model(() -> Gurobi.Optimizer(env)
    optimize!(model)
end
```

> which makes reading my code messages and monitoring the execution progress difficult.

Turn off Gurobi logging? `set_silent(model)`.

**Comment by delft52** [comment]
> > Is there a way to set the Gurobi TimeLimit globally in the code
> 
> No. Although you might be able to re-use an `Env`. (I didn't test this)
> 
> ```julia
> env = Gurobi.Env()
> GRBsetdblparam(env, "TimelImit", 1.0)
> 
> for _ in 1:3
>     model = Model(() -> Gurobi.Optimizer(env)
>     optimize!(model)
> end
> ```
> 
> > which makes reading my code messages and monitoring the execution progress difficult.
> 
> Turn off Gurobi logging? `set_silent(model)`.

Thanks. GRBsetdblparam seems to work for TimeLimit globally, but it gives the following warning: "WARNING: redefinition of constant GRB_ENV. This may fail, cause incorrect answers, or produce other errors." And set_silent didn't stop the loop messages.

**Comment by odow** [comment]
> WARNING: redefinition of constant GRB_ENV. This may fail, cause incorrect answers, or produce other errors

That wasn't part of my code. 

If you copied https://github.com/jump-dev/Gurobi.jl#reusing-the-same-gurobi-environment-for-multiple-solves, then only run `const GRB_ENV = Gurobi.Env()` once.

> And set_silent didn't stop the loop messages.

You can also use `env = GurobiEnv(output_flag = 0)`.

**Comment by delft52** [comment]
> > WARNING: redefinition of constant GRB_ENV. This may fail, cause incorrect answers, or produce other errors
> 
> That wasn't part of my code.
> 
> If you copied https://github.com/jump-dev/Gurobi.jl#reusing-the-same-gurobi-environment-for-multiple-solves, then only run `const GRB_ENV = Gurobi.Env()` once.
> 
Yes, I already had "const GRB_ENV = Gurobi.Env()" in my code and added "GRBsetdblparam(GRB_ENV, "TimelImit", 1)" after it. I think the warning was because of the "const". After removing it, there's no warning. 
> > And set_silent didn't stop the loop messages.
> 
> You can also use `env = GurobiEnv(output_flag = 0)`.
This works, and it resolved the original issue. Even with the local settings (TimeLimit set in the model in the loop rather than globally), there are no messages anymore. It seems that setting the OutputFlag to 0 locally in the model only suppresses the MIPgap update reports but setting it to 0 in ENV globally, suppresses all Gurobi messages. 
Many thanks!

**Comment by odow** [comment]
> but setting it to 0 in ENV globally, suppresses all Gurobi messages

Yes, I think this was a bug in the upstream Gurobi solver that may get fixed in future.

> This works, and it resolved the original issue

Great. I'll close this issue then. Please use the community forum if you have other questions, https://discourse.julialang.org/c/domain/opt/13, we try to reserve GitHub issues for bug reports and feature requests.
