### ISSUE TITLE
Working with docker gurobi/compute

### ISSUE THREAD

**Issue by aferragu** [jump-dev/Gurobi.jl#473]
Hi:
I would like to offload all computations in Julia/JuMP to a Gurobi docker instance of gurobi/compute. However, I don't see in Gurobi.jl a friendly way of creating a Gurobi.Env with a server address attached to it.
Of course, one can get away by using tha whole C API wrapped by Gurobi.jl, but I think having a nice inner constructor for Env that sets the server address and passwotd if needed would be desirable. From my understanding this should be done before starting the environment, otherwise the library will look for a local license, whereas in this case the license lives in the docker instance.

Maybe there is another simple way that I missed entirely. Sorry if that's the case.

**Comment by odow** [comment]
The current code calls `GRBemptyenv`
https://github.com/jump-dev/Gurobi.jl/blob/3d149a43cafd1f8746b7ef196d8134b6afaebb70/src/MOI_wrapper/MOI_wrapper.jl#L87-L122

I'll review a PR for other constructors, but I'm not sure what is required.

**Comment by aferragu** [comment]
Ok. An unstarted empty environment may be a good place to start. But let me try it locally and maybe I can come up with something better. I already have it working on c++ so it should be doable

**Comment by aferragu** [comment]
I created #474 to address this. Hopefully you can look at it @odow!

**Comment by aferragu** [comment]
Closed in #474
