### ISSUE TITLE
Julia thread limit is not respected

### ISSUE THREAD

**Issue by rafaelmartinelli** [jump-dev/Gurobi.jl#476]
When running a script limiting the number of threads like `julia --threads=1 test.jl`, Gurobi does not respect this value.
I know its possible to limit using `optimizer_with_attributes`, but I don't have control of user code.

**Comment by odow** [comment]
Julia threads are not the same as Gurobi threads. The way to control Gurobi's thread use is via the Gurobi parameters. Changing the number of Julia threads will have no effect.

**Comment by odow** [comment]
Closing because there's nothing actionable. Julia threads do not control Gurobi threads.
