### ISSUE TITLE
Problem reusing the same Gurobi Environment when using a package

### ISSUE THREAD

**Issue by this-josh** [jump-dev/Gurobi.jl#482]
I've followed the guidance in the readme on how to [reuse the same Gurobi environment](https://github.com/jump-dev/Gurobi.jl#reusing-the-same-gurobi-environment-for-multiple-solves). For some reason I'm having trouble using it within a package. If I define my code in the REPL or in a file and then import it using `include("my_file.jl")` everything works fine. But putting the code into a package and importing it causes a Gurobi 10002 error.

```julia
ERROR: LoadError: Gurobi Error 10002: 
Stacktrace:
  [1] _check_ret
    @ ~/.julia/packages/Gurobi/VPomg/src/MOI_wrapper/MOI_wrapper.jl:368 [inlined]
  [2] empty!(model::Gurobi.Optimizer)
    @ Gurobi ~/.julia/packages/Gurobi/VPomg/src/MOI_wrapper/MOI_wrapper.jl:436
  [3] Gurobi.Optimizer(env::Gurobi.Env; enable_interrupts::Bool)
    @ Gurobi ~/.julia/packages/Gurobi/VPomg/src/MOI_wrapper/MOI_wrapper.jl:341
  [4] Optimizer
    @ ~/.julia/packages/Gurobi/VPomg/src/MOI_wrapper/MOI_wrapper.jl:318 [inlined]
  [5] #1
    @ ~/grb/src/o.jl:6 [inlined]
  [6] _instantiate_and_check(optimizer_constructor::grb.var"#1#2")
    @ MathOptInterface ~/.julia/packages/MathOptInterface/kCmJV/src/instantiate.jl:70
  [7] instantiate(optimizer_constructor::Function; with_bridge_type::Type{Float64})
    @ MathOptInterface ~/.julia/packages/MathOptInterface/kCmJV/src/instantiate.jl:125
  [8] set_optimizer(model::Model, optimizer_constructor::Function; add_bridges::Bool)
    @ JuMP ~/.julia/packages/JuMP/Psd1J/src/optimizer_interface.jl:110
  [9] set_optimizer
    @ ~/.julia/packages/JuMP/Psd1J/src/optimizer_interface.jl:103 [inlined]
 [10] set_solver(model::Model)
    @ grb ~/grb/src/o.jl:6
 [11] top-level scope
    @ ~/grb/not_working.jl:5
in expression starting at~/grb/not_working.jl:5
```

The minimal working example can be seen [here](https://github.com/this-josh/grb), with the file `not_working.jl` demonstrating the problematic implementation, and `working.jl` and `working2.jl` working as expected.

**Comment by this-josh** [comment]
Thank you, that has worked. The lack of a Julia error led made me to incorrectly presume it must be something Gurobi specific.

**Comment by odow** [comment]
Defining module-level constants that interact with C code is a bit of a footgun in Julia, but there's not really any way for the compiler to tell if you're doing something that's bad or not.
