### ISSUE TITLE
A fresh instalation using Gurobi v9.5 does not uses the correct version. 

### ISSUE THREAD

**Issue by felipemarkson** [jump-dev/Gurobi.jl#498]
Hi!

I'm trying to use the `Gurobi.jl` v0.11.5 with `JuMP` and Gurobi v9.5, and an error shows that I'm using the wrong version of the Gurobi.

[EDIT 1] I guess the problem is with this hardcoded version, but I'm not sure about it.
https://github.com/jump-dev/Gurobi.jl/blob/2a279d2749eaa49401a7642b63a248f2e7f47dc6/src/Gurobi.jl#L18-L24

[EDIT 2] I already try the the Gurobi's docs [Testing your license](https://www.gurobi.com/documentation/current/quickstart_linux/testing_your_license.html) and everything is fine.

[EDIT 3] When I try to find what Gurobi the `Gurobi.jl` is using, it seems that the `Gurobi.jl` get the lib from somewhere else.
```shell
julia> Gurobi.libgurobi
"~/.julia/artifacts/e1ea344a512fd4849fd788ddbe04e5f2c0d986b2/gurobi1000/linux64/lib/libgurobi100.so"
```
## Stacktrace

![image](https://user-images.githubusercontent.com/47871564/216382178-a38e4bfc-331b-4350-ab28-58e0041361e2.png)

## Useful information
OS: Fedora Linux 37 (Workstation Edition) x86_64
Kernel: 6.0.16-300.fc37.x86_64

**Comment by felipemarkson** [comment]
The problem was that I was not running `Pkg.build("Gurobi")`.

Maybe, this could be useful information to place in README.

**Comment by odow** [comment]
You likely installed Gurobi.jl without first setting `GUROBI_HOME`.  And yeah, once you change `GUROBI_HOME` you need to re-run `Pkg.build`.
