### ISSUE TITLE
Error building `Gurobi`: ERROR: LoadError: Unable to locate Gurobi installation. 

### ISSUE THREAD

**Issue by smodops** [jump-dev/Gurobi.jl#506]
I have installed Julia 1.8.5 and Gurobi 9.0.3 (given that only versions 9.0 and 9.1 are supported), but I am having issue building the Gurobi package. I did update the GUROBI_HOME environment (both by updating my bash_profile on Mac and also manually adding it in Julia), but I am still getting the "Unable to locate Gurobi installation" error. I know that this is not a new issue, but my extensive google search for possible solutions did not help. I'd appreciate it if someone could offer a solution. 

Here is the exact output from the Julia in my Mac terminal:

julia> ENV["GUROBI_HOME"]
"/Library/gurobi903/mac64"

(@v1.8) pkg> build Gurobi
    Building Gurobi → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/aac05324d46b53289ccb05510b05b4a56ffd3ed5/build.log`
ERROR: Error building `Gurobi`: 
ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
open an issue at https://github.com/jump-dev/Gurobi.jl and post the full
print-out of this diagnostic attempt.

Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ ~/.julia/packages/Gurobi/BAtIN/deps/build.jl:165
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [4] top-level scope
   @ none:5
in expression starting at /Users/sajadmodaresi/.julia/packages/Gurobi/BAtIN/deps/build.jl:159

**Unable to locate Gurobi installation. Running some common diagnostics.**

Gurobi.jl only supports the following versions:

 - gurobi91
 - gurobi90

Did you download and install one of these versions from gurobi.com?
Installing Gurobi.jl via the Julia package manager is _not_ sufficient!

Found GUROBI_HOME =  /Library/gurobi903/mac64

Does this point to the correct install location?

We're going to look for the Gurobi library in this directory:
    /Library/gurobi903/mac64/lib

That directory has the following files:

 - /Library/gurobi903/mac64/lib/.DS_Store
 - /Library/gurobi903/mac64/lib/gurobi-javadoc.jar
 - /Library/gurobi903/mac64/lib/gurobi.jar
 - /Library/gurobi903/mac64/lib/gurobi.py
 - /Library/gurobi903/mac64/lib/gurobi90.netstandard20.dll
 - /Library/gurobi903/mac64/lib/gurobi90.netstandard20.xml
 - /Library/gurobi903/mac64/lib/libGurobiJni90.jnilib
 - /Library/gurobi903/mac64/lib/libgurobi90.dylib
 - /Library/gurobi903/mac64/lib/libgurobi90_light.dylib
 - /Library/gurobi903/mac64/lib/libgurobi_c++.a
 - /Library/gurobi903/mac64/lib/libgurobi_g++4.2.a
 - /Library/gurobi903/mac64/lib/python2.7
 - /Library/gurobi903/mac64/lib/python3.5
 - /Library/gurobi903/mac64/lib/python3.6
 - /Library/gurobi903/mac64/lib/python3.7
 - /Library/gurobi903/mac64/lib/python3.8
 - /Library/gurobi903/mac64/lib/rootcert.pem

We were looking for (but could not find) a file named like
`libgurobiXXX.so`, `libgurobiXXX.dylib`, or `gurobiXXX.dll`.

You should set the `GUROBI_HOME` environment variable to point to the
install location then try again. For example (updating the path to the
correct location if needed):
```
# On Windows, this might be
ENV["GUROBI_HOME"] = "C:\\Program Files\\gurobi910\\win64\\"
import Pkg
Pkg.add("Gurobi")
Pkg.build("Gurobi")

# On OSX, this might be
ENV["GUROBI_HOME"] = "/Library/gurobi910/mac64/"
import Pkg
Pkg.add("Gurobi")
Pkg.build("Gurobi")

# On Unix, this might be
ENV["GUROBI_HOME"] = "/opt/gurobi910/linux64/"
import Pkg
Pkg.add("Gurobi")
Pkg.build("Gurobi")
```
**Note: your path may differ. Check which folder you installed the Gurobi
binary in, and update the path accordingly.**

**Comment by odow** [comment]
What is `import Pkg; Pkg.status("Gurobi")`?

It looks like you've installed an old version of Gurobi.jl. Try updating your packages.

Is your Mac an M1?

**Comment by smodops** [comment]
Thanks for your quick reply. 

My Mac is an M2. 

This is what I got for the Gurobi status and after trying to update the package: 

julia> import Pkg; Pkg.status("Gurobi")
Status `~/.julia/environments/v1.8/Project.toml`
⌃ [2e9cd046] Gurobi v0.9.14
Info Packages marked with ⌃ have new versions available and may be upgradable.

(@v1.8) pkg> up Gurobi
    Updating registry at `~/.julia/registries/General.toml`
   Installed ArrayInterface ─ v7.3.1
  No Changes to `~/.julia/environments/v1.8/Project.toml`
    Updating `~/.julia/environments/v1.8/Manifest.toml`
  [4fba245c] ↑ ArrayInterface v7.2.1 ⇒ v7.3.1
Precompiling project...
  5 dependencies successfully precompiled in 5 seconds. 92 already precompiled. 3 skipped during auto due to previous errors.

(@v1.8) pkg> st Gurobi
Status `~/.julia/environments/v1.8/Project.toml`
⌃ [2e9cd046] Gurobi v0.9.14
Info Packages marked with ⌃ have new versions available and may be upgradable.

**Comment by odow** [comment]
> My Mac is an M2.

Old versions of Gurobi do not support this architecture. You need at least Gurobi 10.0.

**Comment by smodops** [comment]
Thanks so much for the suggestions. I installed Gurobi 10.0.1. When trying to install Gurobi.jl v1.0.0, the package GLPKMathProgInterface was interfering, so I removed that package and then I could build the Gurobi package. That FINALLY solved the issue! Thanks again for your quick help.

**Comment by odow** [comment]
> GLPKMathProgInterface

You shouldn't need this package for anything. It's very old, deprecated, and unmaintained. Just use `GLPK.jl` for anything GLPK-related now.

> That FINALLY solved the issue! Thanks again for your quick help.

No problem :smile: 

I'll close this issue. If you have other questions, please post on the discourse forum: https://discourse.julialang.org/c/domain/opt/13
