### ISSUE TITLE
Package does not install without Gurobi installed

### ISSUE THREAD

**Issue by gmantegna** [jump-dev/Gurobi.jl#517]
I work on development of an open source Julia package for power systems optimization, [GenX](https://github.com/GenXProject/GenX), which allows users to use multiple solvers including Gurobi. However, we are currently not able to include Gurobi.jl in our dependencies, because if we did, then users who did not have Gurobi installed would encounter an error during installation of Gurobi.jl. This is annoying for those users of our package who do want to use Gurobi as they have to manually add the package, and uncomment the "using Gurobi" line of code in the package itself. This last step in particular is problematic for those seeking to use the package without cloning the repo and modifying code. Would it be possible to add functionality to Gurobi.jl that would allow users to install the package without having Gurobi installed? Perhaps a warning could be thrown instead of an error?

**Comment by odow** [comment]
See https://github.com/jump-dev/CPLEX.jl/issues/406 for the discussion I had with other GenX developers on this.

You can set the `GUROBI_JL_SKIP_LIB_CHECK` environment variable to skip the error. Documented in the installation section https://github.com/jump-dev/Gurobi.jl#installation

**Comment by odow** [comment]
> users of our package who do want to use Gurobi as they have to manually add the package, and uncomment the "using Gurobi" line of code in the package itself

To reiterate https://github.com/jump-dev/CPLEX.jl/issues/406#issuecomment-1217172041: the approach of hard-coding the solvers into the package should be changed:

https://github.com/GenXProject/GenX/blob/ae19f20978255a3cfdc40e2e0292cf322095a90d/src/GenX.jl#L42

In the run file of a user's code, they should write something like (entirely made up functions):
```julia
using GenX, Gurobi
GenX.run(optimizer = Gurobi.Optimizer)
```
Don't do
```julia
using GenX
GenX.run(optimizer = "gurobi")
```
where the dispatch happens inside GenX.

**Comment by mlubin** [comment]
Package extensions (https://docs.julialang.org/en/v1/manual/code-loading/#man-extensions) also provide a solution to this problem.

**Comment by gmantegna** [comment]
Thanks so much all. We are going to try to implement @odow's suggestion.
