### ISSUE TITLE
Add general constraints support

### ISSUE THREAD

**Issue by votroto** [jump-dev/Gurobi.jl#554]
No idea if this is a reasonable request, but it would be really nice to have support for Gurobi's [general function constraints](https://www.gurobi.com/documentation/11.0/refman/c_agc_log.html). They can now be solved exactly without piecewise lin approx.

There are a few such as:
- ln(x) = y
- log(x) = y
- sin(x) = y
- cos(x) = y
- tan(x) = y

which might not be impossible. 

It's always the same pattern "one variable in a function equals another variable." If that's possible, bridges might actually make it nicer to use than even gurobi's interface.

**Comment by odow** [comment]
The current suggestion is to use the C API: https://github.com/jump-dev/Gurobi.jl?tab=readme-ov-file#the-c-api-from-jump

A future version of Gurobi may support general nonlinear constraints, in which case we would support `MOI.ScalarNonlinearFunction`. 

But we don't be adding general constraint support in the near term.

**Comment by odow** [comment]
Closing as won't-fix. (But if you're interested, take a read of https://github.com/jump-dev/MathOptInterface.jl/issues/2402)
