### ISSUE TITLE
Proper way to work with v1.3.0

### ISSUE THREAD

**Issue by sstroemer** [jump-dev/Gurobi.jl#570]
## Initial error

I hit the following error on a new environment, after adding `Gurobi.jl`

```text
Failed to precompile Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b] to "/home/user/.julia/compiled/v1.10/Gurobi/jl_giWYas".
ERROR: LoadError: SystemError: opening file "/home/user/.julia/packages/Gurobi/uP4zR/deps/deps.jl": No such file or directory
```

After checking here, I figured out, that this might be related to the new version (that I didn't know about) - it works when I manually go down to `v1.2.3`. Now, I've seen that due to the usage of `Gurobi_jll.jl` the installation process changed, which is where my problem is now:

- I have a valid Gurobi license, that is bound to my computer
- I do not have Gurobi binaries "installed" (at least, not in some fixed, global path that I could pass to `GUROBI_HOME`)
- I can't easily run `grbgetkey` everytime I set up a new env, and I can't point it manually to an env

I somewhat assume that [this lookup in `Gurobi_jll.jl`](https://github.com/jump-dev/Gurobi_jll.jl/blob/df1a1f081c3856474d71157918ea35cfafcf5107/src/wrappers/x86_64-linux-gnu.jl#L25) may be the culprit?

## Resolving it

Therefore:

- Would it be possible to, e.g., let me pass a path to the `gurobi.lic` file myself?
- If the above is possible, would it be a QoL for unaware users to check the default paths for Win/Mac/Linux that `grbgetkey` uses, before throwing an error (if no manual setup was done)
- I could not run this "built-in" execution of `grbgetkey` but I (believe to) remember, that the normal version allows the user to specify the name/path where it writes the license file - could this potentially lead to further errors if it's hard coded there?

---

## Random thoughts

If my guess is entirely wrong, and I did something else wrong to trigger the initial error, ignore the following; with that said:

- I didn't have time to check it more thoroughly right now, but maybe it would also be possible to catch that "user mistake" and present a more verbose error message?
- I know this change does not directly break the API of `Gurobi.jl`, but it seems to "break" the way it's installed. What happens if I update an existing env, or do a fresh install of one that I cloned? A lot of projects may have compat bounds that allow `1.3.0` since they are only bound to the major not changing.

**Comment by odow** [comment]
The no `deps.jl` error is weird. This can really happen only if you tried to install locally and got an error message?

Try `] build Gurobi`.

**Comment by sstroemer** [comment]
Huh, weird stuff. Thanks! I don't really understand what I messed up, but that fixed it. Disregard the rest :grin:
