### ISSUE TITLE
README could have clearer instructions for WLS license

### ISSUE THREAD

**Issue by djsmedes** [jump-dev/Gurobi.jl#571]
The current README has a section just under the "Installation" header that talks about how to install a license. I'm not sure exactly which of the licensure mechanisms these instructions are for, but they don't appear to be needed for a WLS license. All you seem to need is the `gurobi.lic` file to exist in one of the places Gurobi will check for it - https://support.gurobi.com/hc/en-us/articles/360013417211-Where-do-I-place-the-Gurobi-license-file-gurobi-lic - and then 

```julia
import Pkg
Pkg.add("Gurobi")
```

...seems to work just fine.

Can anyone confirm that this is all that's needed? I've got my install to work, but I spent 30 minutes tinkering with code similar to this part of the README:

```julia
import Pkg
Pkg.add("Gurobi_jll")
import Gurobi_jll
# Replace the contents xxxxx with your actual key
key = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
run(`$(Gurobi_jll.grbgetkey()) $key`)
```

And none of my attempts worked - you get UUID-shaped values from the WLS license file, but I don't think they're the same as whatever the "key" is that's needed for the above code to work.

Then, I just moved the `gurobi.lic` file to my home directory (MacOS) and did `Pkg.add("Gurobi")` and it worked flawlessly.

So the issue here is that the README isn't clear enough about what type of license key it's talking about, and may lead people on a bit of a goose chase when there may be a much simpler solution for them.

I'm happy to open a PR with some suggested new language in that section if this makes sense to people more knowledgeable than me. I'm very new to Julia and Gurobi and could easily have missed something.

**Comment by odow** [comment]
You're right, this part of the README doesn't apply to the WLS license. (I didn't think these were in widespread usage, but perhaps they are.) The instructions apply to the older single-machine type licenses that you got a key and needed to verify.

I'm happy to review a PR if you want to make one.

**Comment by djsmedes** [comment]
No idea if they are in widespread usage, but to my eye there's a subtle push towards them on Gurobi's website - the fact that they are portable, designed to be easy to use in containers, etc etc, makes me think this might be a direction they are moving toward. I could totally just be seeing what I want to see, though. 

Either way, a few sentences changed in the README here is easy enough - I'll make a PR in the next week or so and add you as a reviewer. Thank you!

**Comment by simonbowly** [comment]
There's detailed instructions here for setting up the various license types. The only exception for JuMP users should be the alternative way of running `grbgetkey` if `Gurobi_jll` is installed and the license needs it.

https://support.gurobi.com/hc/en-us/articles/12872879801105-How-do-I-retrieve-and-set-up-a-Gurobi-license

**Comment by odow** [comment]
I've opened a PR: https://github.com/jump-dev/Gurobi.jl/pull/572
