### ISSUE TITLE
Gurobi.jl doesn't support `MOI.set(model, MOI.SolutionLimit(), nr_solutions)`

### ISSUE THREAD

**Issue by langestefan** [jump-dev/Gurobi.jl#578]
I am trying to set a solution limit like this:
```
model = Model(Gurobi.Optimizer)
MOI.set(model, MOI.SolutionLimit(), 4)
```

Which returns:
> MathOptInterface.UnsupportedAttribute{MathOptInterface.SolutionLimit}: Attribute MathOptInterface.SolutionLimit() is not supported by the model.

I believe Gurobi should support this feature?

**Comment by odow** [comment]
This was only added to MathOptInterface v1.21.0. No one has added support for it to Gurobi.jl yet. PRs accepted.
