### ISSUE TITLE
ListOfModelAttributesSet does not include callbacks

### ISSUE THREAD

**Issue by bachdavi** [jump-dev/Gurobi.jl#579]
Hey! 

As the title says, we get an error when printing in `LP` format with Gurobi:
```
ERROR: MathOptInterface.UnsupportedAttribute{Gurobi.CallbackFunction}: Attribute Gurobi.CallbackFunction() is not supported by the model.
Stacktrace:
```
Here is a MRE on the latest version `1.3.1` of Gurobi.jl.

```
import Gurobi
import MathOptInterface as MOI

model = MOI.instantiate(() -> Gurobi.Optimizer(); with_cache_type = Float64, with_bridge_type = Float64)
MOI.set(model, Gurobi.CallbackFunction(), () -> nothing)
MOI.Utilities.loadfromstring!(
           model,
           """
       variables: x, y, z
       minobjective: 1.0 * x + 1.0 * y + 1.0 * z
       c1: x + y == 2.0
       c2: x + y + z >= 0.0
       c3: 1.0 * x * x + -1.0 * y * y + -1.0 * z * z >= 0.0
       x >= 0.0
       y >= 0.0
       z >= 0.0
       """)
print_options = (; format = MOI.FileFormats.FORMAT_LP)
dest = MOI.FileFormats.Model(; print_options...)
MOI.copy_to(dest, model)
```

If I omit the line that sets the `Gurobi.CallbackFunction`, printing works. Also using the `Gurobi.Optimizer()` directly instead of a cached optimizer works.

Edit: I thought we could set `CallbackFunction` to `nothing` before printing but that unfortunately resets the optimizer state. Printing works correctly in that case.

Thank you!

**Comment by odow** [comment]
This error is expected behavior. The LP writer does not support serializing `Gurobi.CallbackFunction` to disk.

I think this is just asking for a way to unset the CallbackFunction.

`Gurobi.Optimizer` works because we don't properly report that a callback is set (this is a separate bug):
https://github.com/jump-dev/Gurobi.jl/blob/9bafe7d3e4ed198b97836362a62bb48a14d408bc/src/MOI_wrapper/MOI_wrapper.jl#L748-L764

**Comment by odow** [comment]
Why do you need this?

**Comment by bachdavi** [comment]
Thank you for the response!

I see! We need this as we are using Gurobi callbacks to store some state while solving and depending on the user query we will also print the problem. Yes unsetting the callback without resetting the optimizer state would solve our problem. I've tried a bunch of things but so far no luck. Do you have any pointers?

**Comment by odow** [comment]
If you know that you're using Gurobi
```julia
Gurobi.GRBwrite(JuMP.unsafe_backend(model), "model.lp")
```

**Comment by odow** [comment]
Perhaps there is an argument to exclude. I'll discuss this at our next monthly meeting

**Comment by odow** [comment]
Call says:

* Check/make set to `nothing` support. We might need to make `UniversalFallback` support this.
* otherwise check if the ModelFilter works
* We should error because the callback is part of the model

**Comment by odow** [comment]
Just to follow up on this. The next release of MOI will support `MOI.set(model, Gurobi.CallbackFunction(), nothing)` as a way to remove the callback.

**Comment by bachdavi** [comment]
> Just to follow up on this. The next release of MOI will support `MOI.set(model, Gurobi.CallbackFunction(), nothing)` as a way to remove the callback.

Thanks @odow ❤️
