### ISSUE TITLE
Gurobi.jl indicates a wrong version in the logfile

### ISSUE THREAD

**Issue by foreverdyz** [jump-dev/Gurobi.jl#583]
My PC (win 11) only installed Gurobi 10.0.1 and my license is for version 10. But every time when I used gurobi in JuMP and wrote out the logfile, JuMP is using Gurobi 11.0.2 as follows,
<img width="438" alt="fig1" src="https://github.com/user-attachments/assets/d0ab4d05-2d96-4084-8cbc-1802e68d24dd">

Is it only a bug that JuMP writes it wrong? Or some other issues.

**Comment by odow** [comment]
We automatically installed Gurobi v11.0.2 for you.

To opt-out, see https://github.com/jump-dev/Gurobi.jl?tab=readme-ov-file#manual-installation

**Comment by foreverdyz** [comment]
Ah, thank you. I solved the problem. Could you kindly mention that in the doc? Since the newest version is 11.0.3. I was a bit confused about that before.

**Comment by odow** [comment]
![image](https://github.com/user-attachments/assets/2790aa73-b079-4154-ac82-4ac6df4eda61)

**Comment by foreverdyz** [comment]
Ok, I missed that. Thank you
