### ISSUE TITLE
Gurobi's "Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored" is printed upon JuMP.@constraint() rather than during JuMP.optimize!()

### ISSUE THREAD

**Issue by WalterMadelim** [jump-dev/Gurobi.jl#598]
If you want to eliminate printing, you have to use `JuMP.set_silent(model)` **immediately after** creating that `model`.
If you are setting `JuMP.set_silent(model)` just before `JuMP.optimize!(model)`, you may still see the warning information being printed.

**Comment by WalterMadelim** [comment]
From JuMP's perspective, 
it would be wonderful if we could have a `concise_inner_product` function (or macro) shown as follows

```julia
model = Model()
JuMP.@variable(model, x[1:4])
c = [2.0, -1e-14, 1e-12, 1e-13] # a disagreeable coefficient vector
my_tolerance = 5e-13 # 5e-13 is between 1e-12 and 1e-13
# the current way is to build an Affine expression is
LinearAlgebra.dot(c, x) # returns 2 x[1] - 1.0e-14 x[2] + 1.0e-12 x[3] + 1.0e-13 x[4], which is (although correct) prone to Gurobi's Warning
# It should be wonderful if there is such a function 
concise_inner_product(c, x; atol = my_tolerance) # returns c[1] * x[1] + c[3] * x[3], whose type is AffExpr (alias for JuMP.GenericAffExpr{Float64, JuMP.GenericVariableRef{Float64}})

```

**Comment by simonbowly** [comment]
It looks like a combination of [map_coefficients_inplace!](https://jump.dev/JuMP.jl/stable/api/JuMP/#map_coefficients_inplace!) and [drop_zeros!](https://jump.dev/JuMP.jl/stable/api/JuMP/#drop_zeros!) would do the trick for cleaning up your linear expressions before adding them as lazy constraints.

I would be cautious here though. Gurobi is warning you about this for a reason. Sure, you can clean out the 1e-13 coefficients to avoid the warning, but then it seems likely you are also introducing many 1e-12 or similar-sized coefficients which may then cause numerical trouble. You really need to understand the source of these small coefficients and whether they are actually important to the constraint you are adding.

**Comment by WalterMadelim** [comment]
@simonbowly It's unfortunate that the very small coefficient is precisely offered by Gurobi, retrieved via JuMP.dual(), in another program, where the underlying solver is Gurobi. The full source code is https://github.com/WalterMadelim/p8f.jl/blob/main/src/tmp_1.jl
You can have a try and observe its output in julia REPL. This program should be correct and can converge after about 5min.

I know this drop_zeros!(), but it is used for ordinary model. Now I want to use expression in a callback function, I don't know how to use it though. (see line 306-308 in the abovementioned tmp_1.jl)

**Comment by WalterMadelim** [comment]
@simonbowly I've followed your advice by utilizing these 2 functions, And the code in the link is updated. 
But they didn't work. The warning still exists.

**Comment by simonbowly** [comment]
The docs for map_coefficients and drop_zeros imply they should work on any expression, so I don't see a reason this wouldn't work when building an expression within a callback. Try inspecting the expressions in your callback before adding them.

The warnings are printed by Gurobi. Normally when building a model they would be displayed only once, even if multiple constraints had this problem. We'll take a look and see if we can improve this behaviour for lazy constraints.

I'm not aware of a way to filter specific output lines within Julia's REPL. I would try writing to a log file instead, then the lines can be easily filtered using grep or a similar tool.

**Comment by WalterMadelim** [comment]
@simonbowly Thanks for your information. But I'm pretty sure that a bug is here.
please copy my code https://github.com/WalterMadelim/p8f.jl/blob/main/src/tmp_1.jl to your Julia REPL to see the outcomes.
This time I firstly set_silent and then optimize (with callback), and the aforementioned warning line still exists. (see line 328-331).

The program is correct and can converge, within 5 minutes you should see the program is over and returned to REPL, with `lb = 1.229989`, and you can see that `gap = 0.027` which is less than the tolerance `UPDTOL = 0.04`.

The continual warning line being printed phenomenon occurs after around 90 seconds.

A preview of the output is as follows
```julia
[ Info: lb = 1.2299776242676796
[ Info: lb = 1.2299776242676796
[ Info: lb = 1.2299776242676796
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
[ Info: lb = 1.2299776242676796
[ Info: lb = 1.2299779057117621
[ Info: lb = 1.2299779057117621
[ Info: lb = 1.2299779057117621
[ Info: lb = 1.2299779057117621
[ Info: lb = 1.2299779057117621
[ Info: lb = 1.2299779057117621
[ Info: lb = 1.2299779057117621
[ Info: lb = 1.2299779057117621
[ Info: lb = 1.2299779057117621
[ Info: lb = 1.2299779057117621
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
[ Info: all S⋅A⋅T🥑gap = 0.027059259393362883 = 0.027058857552993906 - -4.018403689760806e-7 🥑UPDTOL = 0.04 🥑lb = 1.2299779057117621

julia> # @optimize_assert_optimal(tr1)

julia> lb = JuMP.objective_value(tr1)
1.229989828617565

julia> @info "lb = $lb"
[ Info: lb = 1.229989828617565

julia> 

```

**Comment by WalterMadelim** [comment]
Might be a Gurobi's bug?
The warning line persists even if C-API is used (instead of JuMP-API).
```julia
function grb_set_silent(m)
    return Gurobi.GRBsetintparam(Gurobi.GRBgetenv(JuMP.backend(m)), Gurobi.GRB_INT_PAR_OUTPUTFLAG, 0) 
end
```

**Comment by WalterMadelim** [comment]
@simonbowly Thanks, I've known the reason. The explanation is updated, in my first comment.

**Comment by simonbowly** [comment]
@WalterMadelim for the future, please do not delete/overwrite your original questions when editing your initial post and comments. It is now impossible for anyone to follow this discussion. Better practice is to append additional comments if you want to give more context, rather than rewriting.

I will assume from your later comments that the warnings were in fact not coming from the lazy constraints, but occurs once for each of the models you are building to derive the lazy constraints. In which case, this is not a Gurobi bug, but a valid warning.

**Comment by WalterMadelim** [comment]
@simonbowly Yes. This issue is not related to callback function with lazy constraints.
As the title suggests, this particular warning is not printed during optimizing, but is printed upon building a constraint.
The small coefficients are from `JuMP.value(x)`, which is essentially provided by Gurobi.
To solve this issue, we can use these functions in practice.
```julia
function jvr6(x) return round(JuMP.value(x); digits = 6) end
function jdr6(x) return round( JuMP.dual(x); digits = 6) end
```
To locate information in the context of multiple models, we can use file logging.
```julia
function clear_log_file(file_string) return open(io -> nothing, file_string, "w") end # open, truncate, close
function set_logfile_for_model(file_string, model) # optional
    JuMP.set_attribute(model, "OutputFlag", 1)
    JuMP.set_attribute(model, "LogToConsole", 0)
    JuMP.set_attribute(model, "LogFile", file_string)
end
```
An successful example can be found at https://github.com/WalterMadelim/p8f.jl/blob/main/src/UnitCom_workable1.jl
