### ISSUE TITLE
Interface completion

### ISSUE THREAD

**Issue by IainNZ** [jump-dev/Gurobi.jl#8]
We already support a lot of the interface, so lets push for 100%. This was taken from the 5.6 Reference Manual: http://www.gurobi.com/documentation/5.6/reference-manual/refman
### Environment Creation and Destruction
- [x] GRBloadenv (as the constructor for Env - consider adding a gurobi_env() function which does same for consistency with style of rest of API, esp. model constructor. Should probably support logfilename as optional argument)
- [ ] GRBloadclientenv (compute server-related - ignore)
- [x] GRBfreeenv
- [ ] GRBgetconcurrentenv
- [ ] GRBdiscardconcurrentenvs
### Model Creation and Modification
- [ ] GRBloadmodel
- [x] GRBnewmodel
- [x] GRBcopymodel
- [x] GRBaddconstr
- [x] GRBaddconstrs
- [x] GRBaddqconstr
- [x] GRBaddqpterms
- [x] GRBaddrangeconstr
- [x] GRBaddrangeconstrs
- [ ] GRBaddsos
- [x] GRBaddvar
- [x] GRBaddvars
- [ ] GRBchgcoeffs
- [ ] GRBdelconstrs
- [ ] GRBdelq
- [ ] GRBdelqconstrs
- [ ] GRBdelsos
- [ ] GRBdelvars
- [x] GRBupdatemodel
- [x] GRBfreemodel
## Model Solution
- [x] GRBoptimize
- [x] GRBcomputeIIS
- [ ] GRBfeasrelax
- [ ] GRBfixedmodel
- [ ] GRBresetmodel
- [ ] GRBsync
### Model Queries
- [ ] GRBgetcoeff
- [ ] GRBgetconstrbyname
- [x] GRBgetconstrs
- [ ] GRBgetenv
- [x] GRBgetq
- [ ] GRBgetqconstr
- [ ] GRBgetsos
- [ ] GRBgetvarbyname
- [ ] GRBgetvars
### Input/Output
- [x] GRBreadmodel
- [ ] GRBread
- [ ] GRBwrite
### Attribute Management
- [ ] GRBgetattrinfo
- [ ] GRBgetintattr
- [ ] GRBsetintattr
- [ ] GRBgetintattrelement
- [ ] GRBsetintattrelement
- [ ] GRBgetintattrarray
- [ ] GRBsetintattrarray
- [ ] GRBgetintattrlist
- [ ] GRBsetintattrlist
- [ ] GRBgetdblattr
- [ ] GRBsetdblattr
- [ ] GRBgetdblattrelement
- [ ] GRBsetdblattrelement
- [ ] GRBgetdblattrarray
- [ ] GRBsetdblattrarray
- [ ] GRBgetdblattrlist
- [ ] GRBsetdblattrlist
- [ ] GRBgetcharattrelement
- [ ] GRBsetcharattrelement
- [ ] GRBgetcharattrarray
- [ ] GRBsetcharattrarray
- [ ] GRBgetcharattrlist
- [ ] GRBsetcharattrlist
- [ ] GRBgetstrattr
- [ ] GRBsetstrattr
- [ ] GRBgetstrattrelement
- [ ] GRBsetstrattrelement
- [ ] GRBgetstrattrarray
- [ ] GRBsetstrattrarray
- [ ] GRBgetstrattrlist
- [ ] GRBsetstrattrlist
### Parameter Management and Tuning
- [ ] GRBtunemodel
- [ ] GRBgettuneresult
- [ ] GRBgetdblparam
- [ ] GRBgetintparam
- [ ] GRBgetstrparam
- [ ] GRBsetdblparam
- [ ] GRBsetintparam
- [ ] GRBsetstrparam
- [ ] GRBgetdblparaminfo
- [ ] GRBgetintparaminfo
- [ ] GRBgetstrparaminfo
- [ ] GRBreadparams
- [ ] GRBwriteparams
### Monitoring Progress - Logging and Callbacks
- [ ] GRBmsg
- [x] GRBsetcallbackfunc
- [ ] GRBgetcallbackfunc
- [x] GRBcbget
- [x] GRBversion
### Modifying Solver Behavior - Callbacks
- [x] GRBcbcut
- [x] GRBcblazy
- [x] GRBcbsolution
- [ ] GRBterminate
### Error Handling
- [x] GRBgeterrormsg
### Advanced simplex routines
- [ ] GRBFSolve
- [ ] GRBBSolve
- [ ] GRBinvColj
- [ ] GRBinvRowi
- [ ] GRBgetBasisHead

**Comment by colinfang** [comment]
This todo list is not updated to reflect the status of the latest Gurobi.jl.

I notice all the `get/set ...attrelement` methods are missing. Do we have plan to add them?

For the moment I have to add those in my own caller site.

```
function get_dblattrelement(model::Gurobi.Model, name::ASCIIString, element::Int)
    a = Array(Float64, 1)
    ret = ccall(
        ("GRBgetdblattrelement", Gurobi.libgurobi), Cint,
        (Ptr{Void}, Ptr{UInt8}, Cint, Ptr{Float64}),
        model, name, element - 1, a
    )
    if ret != 0
        throw(GurobiError(model.env, ret))
    end
    a[1]::Float64
end

function set_dblattrelement!(model::Gurobi.Model, name::ASCIIString, element::Int, v::Real)
    ret = ccall(
        ("GRBsetdblattrelement", Gurobi.libgurobi), Cint,
        (Ptr{Void}, Ptr{UInt8}, Cint, Float64),
        model, name, element - 1, v
    )
    if ret != 0
        throw(GurobiError(model.env, ret))
    end
    nothing
end
```

**Comment by mlubin** [comment]
@colinfang, I'm not aware of any plans to add these. If you need them, please make a pull request.
