### ISSUE TITLE
getsolution() returns infeasible solution for an unbounded problem

### ISSUE THREAD

**Issue by blegat** [jump-dev/Gurobi.jl#80]
On this problem,
```
Min y
s.t. x >= 1
loadproblem!(m, [1. 0.], [-Inf, -Inf], [Inf, Inf], [0., 1.], [1.], [Inf], :Min)
```
calling `optimize!` returns `:Unbounded` and then `getsolution` gives `[6.93747e-310,0.0]` which is not feasible since `x = 6.93747e-310 < 1` (I am using Gurobi 6.51).

However, it seems that in Gurobi `getsolution` gives a feasible solution even for unbounded problem since for the following problem
```
Max x
s.t. x >= 1
x unbounded
y <= -1
loadproblem!(m, [1. 0.], [-Inf, -Inf], [Inf, -1], [1., 0.], [1], [Inf], :Max)
```
`optimize!` returns `:Unbounded` and then `getsolution` returns a feasible solution.

See https://github.com/JuliaOpt/MathProgBase.jl/pull/144

**Comment by joehuchette** [comment]
This is likely a bug with Gurobi that should be reported upstream

**Comment by mlubin** [comment]
I would check on the Gurobi documentation to see if this is expected behavior or not.

**Comment by mlubin** [comment]
MathProgBase will certainly not be making any guarantees that the solvers are unable to satisfy. If the definitions are inconsistent then we should update the MPB definition.

**Comment by blegat** [comment]
I have been thinking about a new MPB status system (Following the discussion on https://github.com/JuliaOpt/Mosek.jl/issues/101).

* `status(m)`: why the solver stopped: `Success`, `UserLimit`, ...
* `isprimalfeasible(m)`:
  * `true` if it is sure that the primal is feasible,
  * `false` if it is sure it is infeasible,
  * throws an error otherwise,

it may do additional computation to determine this, e.g. if Gurobi says Unbounded, we would set the objective to 0 et reoptimize to determine whether it is feasible, what to do is solver dependent.
* `getsolution(m; feasible=true, optimal=true)` would return a solution:

| | `feasible=true`  | `feasible=false` |
| --------- | ------------- | ------------- |
| `optimal=true` | optimal and feasible  | ??? |
| `optimal=false`  | feasible | anything |

The solver should be lazy so in our case of Gurobi/Unbounded, if we ask `getsolution(m, feasible=false, optimal=false)` then it returns whatever it has but if we ask `getsolution(m, feasible=true, optimal=false)` then it sets the objective to zero and do a resolve to find a feasible solution and if we ask `getsolution(m, feasible=true, optimal=true)` it would throw an error.

I am still a little bit unsure about `getsolution`, we may also do `getsolution(m, status::AbstractSolutionStatus)` where `status` is the status we require (e.g. `AnySolutionStatus`, `FeasibleSolutionStatus`, `OptimalSolutionStatus(eps=1e-6)`). and `getsolution` way also return a pair `solution::Vector, status::AbstractSolutionStatus`.

What do you think ? I agree that this asks more to each solver but this kind of thing cannot be put somewhere else than in the solver package since these are solver specific.

**Comment by mlubin** [comment]
I'm not in favor of imposing a requirement in MPB that requires most LP solvers to do extra work in the unbounded case. That could be something that sits on top of MPB, perhaps.
We definitely need to redo MPB statuses though, should be discussed in an issue on the MPB repository.
